//! Native Rust port of `blueprint/src/lib/generated-docs.mjs`.
//!
//! Lane LIB4 (r5 closure): this module has no prior native equivalent.
//! Blueprint B6.5 generated human docs — regenerates `docs/product.md` and
//! `docs/architecture.md` with a generation header (no timestamp,
//! byte-identical on an unchanged repo), per-section provenance, clobber
//! safety (typed `docs_conflict` when a hand-written file lacks the
//! generation marker, falling back to `.agent/docs/`), an optional README
//! pointer block, and `START-HERE.md` retirement on every successful
//! build.
//!
//! `hash-wasm`'s XXH3-128 becomes `xxhash_rust::xxh3::xxh3_128` (already a
//! crate dependency, used the same way elsewhere in this crate, e.g.
//! `identity.rs`). `openStoreReadOnly`/`closeStore` from
//! `../graph/store-sqlite.mjs` become a direct read-only `rusqlite`
//! connection opened by this module itself (mirroring the legacy module's
//! own independent read-only handle, not a call into `store.rs`, which
//! lane rules forbid touching).

use rusqlite::{Connection, OpenFlags};
use serde_json::{json, Value};
use std::fs;
use std::path::Path;
use xxhash_rust::xxh3::xxh3_128;

pub const VERSION: &str = "0.2.0";
const GENERATION_HEADER_PREFIX: &str = "<!-- generated by blueprint";
const MARKER: &str = "<!-- blueprint:docs:start -->";
const END_MARKER: &str = "<!-- blueprint:docs:end -->";
pub const DOC_PATH_PRODUCT: &str = "docs/product.md";
pub const DOC_PATH_ARCHITECTURE: &str = "docs/architecture.md";
const FALLBACK_DIR: &str = ".agent/docs";
const START_HERE_PATH: &str = ".agent/START-HERE.md";

fn id_exclude(path: &str) -> bool {
    path == "README.md" || path == DOC_PATH_PRODUCT || path == DOC_PATH_ARCHITECTURE
}

/// Read the graph manifest from the store's SQLite database directly
/// (read-only), mirroring `readStoredManifest`. Returns `None` when no
/// graph has been built or the read fails for any reason (matching the
/// JS try/catch-to-null fallback).
pub fn read_stored_manifest(root: &Path) -> Option<Value> {
    let db_path = root.join(".agent").join("graph").join("graph.db");
    if !db_path.exists() {
        return None;
    }
    let conn = Connection::open_with_flags(&db_path, OpenFlags::SQLITE_OPEN_READ_ONLY).ok()?;
    let mut stmt = conn
        .prepare("SELECT value FROM generation WHERE key = 'manifest'")
        .ok()?;
    let value: Option<String> = stmt
        .query_row([], |row| row.get(0))
        .ok();
    value.and_then(|v| serde_json::from_str(&v).ok())
}

fn xxh3_hex(input: &str) -> String {
    format!("{:032x}", xxh3_128(input.as_bytes()))
}

/// Stats subset used by [`generated_docs_generation_id`], mirroring
/// `stats?.files` / `stats?.docs` / `stats?.claims` / `stats?.codeRefs`.
#[derive(Debug, Clone, Copy, Default)]
pub struct DocsStats {
    pub files: i64,
    pub docs: i64,
    pub claims: i64,
    pub code_refs: i64,
}

/// Stable identifier for the source set. Mirrors
/// `generatedDocsGenerationId`. `files` are plain path strings (the JS
/// accepts `entry.path ?? entry`; callers here pass the resolved path
/// directly).
pub fn generated_docs_generation_id(
    files: &[String],
    stats: &DocsStats,
    source_signature: &str,
) -> String {
    let mut sorted_paths: Vec<&str> = files
        .iter()
        .map(|s| s.as_str())
        .filter(|p| !p.is_empty() && !id_exclude(p))
        .collect();
    sorted_paths.sort();
    let joined_paths = sorted_paths.join("\n");
    let input = [
        source_signature,
        &joined_paths,
        &stats.files.to_string(),
        &stats.docs.to_string(),
        &stats.claims.to_string(),
        &stats.code_refs.to_string(),
    ]
    .join("\n");
    xxh3_hex(&input)
}

/// Mirrors `generationHeader`.
pub fn generation_header(generation_id: &str) -> String {
    format!(
        "{} {} gen:{} — edit code/docs sources, not this file -->",
        GENERATION_HEADER_PREFIX, VERSION, generation_id
    )
}

/// Mirrors `isGenerated`: a missing file counts as generated (safe to
/// overwrite); an existing file is generated only if its first line
/// carries the generation-header prefix.
pub fn is_generated(target_path: &Path) -> bool {
    let text = match fs::read_to_string(target_path) {
        Ok(t) => t,
        Err(_) => return true,
    };
    let first_line = text.split(['\n']).next().unwrap_or("");
    let first_line = first_line.strip_suffix('\r').unwrap_or(first_line);
    first_line.starts_with(GENERATION_HEADER_PREFIX)
}

fn write_text(path: &Path, body: &str) -> std::io::Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let out = if body.ends_with('\n') {
        body.to_string()
    } else {
        format!("{}\n", body)
    };
    fs::write(path, out)
}

// ── Product doc ─────────────────────────────────────────────────────────

/// Minimal claim shape used by [`product_sections`], mirroring the JS
/// claim object's `{ status, text, source, line }` fields.
#[derive(Debug, Clone)]
pub struct DocClaim {
    pub status: String,
    pub text: String,
    pub source: String,
    pub line: Value,
}

fn product_sections(repo: &str, claims: &[DocClaim], map: &Value, generation_id: &str) -> String {
    let header = generation_header(generation_id);
    let eligible: Vec<&DocClaim> = claims
        .iter()
        .filter(|c| {
            matches!(c.status.as_str(), "implemented" | "partial" | "claim") && !c.text.is_empty()
        })
        .collect();

    let mut by_source: Vec<(String, Vec<&DocClaim>)> = Vec::new();
    for c in &eligible {
        if let Some(entry) = by_source.iter_mut().find(|(k, _)| k == &c.source) {
            entry.1.push(c);
        } else {
            by_source.push((c.source.clone(), vec![c]));
        }
    }
    by_source.sort_by(|a, b| a.0.cmp(&b.0));

    let capability_rows: Vec<String> = by_source
        .iter()
        .take(12)
        .map(|(path, list)| {
            let top = list[0];
            format!(
                "- **{}** — {} _(source: {}:{})_",
                path,
                top.text,
                top.source,
                value_to_display(&top.line)
            )
        })
        .collect();

    let canonical = ["AGENTS.md", "CLAUDE.md", "README.md"];
    let surface_rows: Vec<String> = map
        .get("nodes")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default()
        .into_iter()
        .filter(|n| {
            n.get("kind").and_then(Value::as_str) == Some("doc")
                && n.get("path")
                    .and_then(Value::as_str)
                    .map(|p| canonical.contains(&p))
                    .unwrap_or(false)
        })
        .map(|n| {
            let path = n.get("path").and_then(Value::as_str).unwrap_or("");
            format!("- `{}` _(source: {}:1)_", path, path)
        })
        .take(5)
        .collect();

    let mut lines: Vec<String> = vec![
        header,
        String::new(),
        format!("# {} — Product Overview", repo),
        String::new(),
        "Code-grounded description of what this product is and does. Generated from verified doc claims;".to_string(),
        "audience and positioning statements come **only** from existing repository docs, never invented.".to_string(),
        String::new(),
        "## Capabilities".to_string(),
        String::new(),
        "Plain-language features derived from the verified claim inventory. Each row points back to its source.".to_string(),
        String::new(),
    ];
    if capability_rows.is_empty() {
        lines.push("- _No verified capability claims yet._".to_string());
    } else {
        lines.extend(capability_rows);
    }
    lines.push(String::new());
    lines.push("## Entry points".to_string());
    lines.push(String::new());
    lines.push("User-visible surfaces named by the repository docs:".to_string());
    lines.push(String::new());
    if surface_rows.is_empty() {
        lines.push("- _No canonical entry-point docs found._".to_string());
    } else {
        lines.extend(surface_rows);
    }
    lines.push(String::new());
    lines.push("## Honesty / Gaps".to_string());
    lines.push(String::new());
    lines.push("Items the docs claim but no implementation file references — and the reverse — surface here as".to_string());
    lines.push("findings. If a flow is named in user-facing copy but absent from the code graph, it is listed".to_string());
    lines.push("below, not omitted.".to_string());
    lines.push(String::new());
    lines.push("- _See `.agent/stale.json` for the canonical missing-reference list (provenance: .agent/stale.json)._".to_string());
    lines.push(String::new());

    lines.join("\n")
}

fn value_to_display(v: &Value) -> String {
    match v {
        Value::String(s) => s.clone(),
        Value::Null => String::new(),
        other => other.to_string(),
    }
}

// ── Architecture doc ────────────────────────────────────────────────────

fn markdown_cell(value: &str) -> String {
    let escaped = value.replace('|', "\\|");
    let collapsed = collapse_whitespace(&escaped);
    collapsed.trim().to_string()
}

fn collapse_whitespace(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut last_was_space = false;
    for c in s.chars() {
        if c.is_whitespace() {
            if !last_was_space {
                out.push(' ');
            }
            last_was_space = true;
        } else {
            out.push(c);
            last_was_space = false;
        }
    }
    out
}

fn workflow_step_text(step: &Value) -> String {
    match step {
        Value::String(s) => s.clone(),
        Value::Object(_) => ["name", "component", "label", "step", "id"]
            .iter()
            .find_map(|k| step.get(*k).and_then(Value::as_str))
            .unwrap_or("")
            .to_string(),
        _ => String::new(),
    }
}

fn workflow_steps(flow: &Value) -> Vec<String> {
    match flow {
        Value::String(s) => split_arrow(s),
        Value::Array(items) => items
            .iter()
            .map(workflow_step_text)
            .map(|s| s.trim().to_string())
            .filter(|s| !s.is_empty())
            .collect(),
        Value::Object(_) => {
            let structured = flow
                .get("steps")
                .or_else(|| flow.get("path"))
                .or_else(|| flow.get("components"));
            if let Some(Value::Array(items)) = structured {
                return items
                    .iter()
                    .map(workflow_step_text)
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty())
                    .collect();
            }
            let text = flow
                .get("flow")
                .or_else(|| flow.get("dataFlow"))
                .or_else(|| flow.get("description"));
            match text {
                Some(Value::String(s)) => workflow_steps(&json!(s)),
                _ => Vec::new(),
            }
        }
        _ => Vec::new(),
    }
}

fn split_arrow(s: &str) -> Vec<String> {
    // Mirrors `flow.split(/\s*(?:->|→)\s*/)`.
    let mut parts = Vec::new();
    let mut current = String::new();
    let chars: Vec<char> = s.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        if chars[i] == '-' && chars.get(i + 1) == Some(&'>') {
            parts.push(current.trim().to_string());
            current = String::new();
            i += 2;
        } else if chars[i] == '→' {
            parts.push(current.trim().to_string());
            current = String::new();
            i += 1;
        } else {
            current.push(chars[i]);
            i += 1;
        }
    }
    parts.push(current.trim().to_string());
    parts.into_iter().filter(|s| !s.is_empty()).collect()
}

fn compact_workflow_label(value: &str) -> String {
    let no_backticks = value.replace('`', "");
    let mut label = collapse_whitespace(&no_backticks).trim().to_string();
    if let Some(colon) = label.find(':') {
        if colon > 0 && colon <= 48 && !label[..colon].contains("::") {
            label = label[..colon].to_string();
        }
    }
    label = label.trim_end_matches(|c: char| c == '.' || c == ';' || c == ',' || c.is_whitespace()).to_string();
    // Re-apply the exact JS semantics: only trailing [.;,]\s* is stripped,
    // not arbitrary trailing whitespace beyond that punctuation run. The
    // trim_end_matches above over-strips plain trailing whitespace too,
    // which is harmless here since collapse_whitespace already trimmed.
    let chars: Vec<char> = label.chars().collect();
    if chars.len() > 88 {
        let truncated: String = chars[..85].iter().collect();
        label = format!("{}…", truncated.trim_end());
    }
    label.replace('\\', "/").replace('"', "'").replace('\n', " ")
}

fn component_workflow_mermaid(architecture: &Value) -> Option<String> {
    let data_flow = architecture.get("dataFlow").and_then(Value::as_array).cloned().unwrap_or_default();
    let chains: Vec<Vec<String>> = data_flow
        .iter()
        .map(workflow_steps)
        .map(|steps| {
            steps
                .iter()
                .map(|s| compact_workflow_label(s))
                .filter(|s| !s.is_empty())
                .collect::<Vec<String>>()
        })
        .filter(|steps: &Vec<String>| steps.len() >= 2)
        .collect();
    if chains.is_empty() {
        return None;
    }

    let mut ids: Vec<(String, String)> = Vec::new();
    let mut edges: Vec<String> = Vec::new();
    let id_of = |ids: &[(String, String)], label: &str| -> Option<String> {
        ids.iter().find(|(l, _)| l == label).map(|(_, id)| id.clone())
    };
    for chain in &chains {
        for label in chain {
            if id_of(&ids, label).is_none() {
                let id = format!("c{}", ids.len());
                ids.push((label.clone(), id));
            }
        }
        for pair in chain.windows(2) {
            let a = id_of(&ids, &pair[0]).unwrap();
            let b = id_of(&ids, &pair[1]).unwrap();
            let edge = format!("{} --> {}", a, b);
            if !edges.contains(&edge) {
                edges.push(edge);
            }
        }
    }

    let mut lines = vec![
        "flowchart LR".to_string(),
        "  %% component workflow from .agent/understanding.json".to_string(),
    ];
    lines.extend(ids.iter().map(|(label, id)| format!("  {}[\"{}\"]", id, label)));
    lines.extend(edges.iter().map(|edge| format!("  {}", edge)));
    Some(lines.join("\n"))
}

fn architecture_sections(repo: &str, _map: &Value, stale: &Value, understanding: &Value, generation_id: &str) -> String {
    let header = generation_header(generation_id);
    let default_arch = json!({});
    let architecture = understanding.get("architecture").unwrap_or(&default_arch);

    let component_rows: Vec<String> = architecture
        .get("components")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default()
        .iter()
        .map(|component| {
            let name = markdown_cell(
                component
                    .get("name")
                    .or_else(|| component.get("component"))
                    .and_then(Value::as_str)
                    .unwrap_or("Unnamed component"),
            );
            let note = markdown_cell(
                component
                    .get("note")
                    .or_else(|| component.get("role"))
                    .and_then(Value::as_str)
                    .unwrap_or(""),
            );
            let evidence = markdown_cell(
                component
                    .get("evidence")
                    .and_then(Value::as_str)
                    .unwrap_or("Undetermined — no evidence recorded"),
            );
            if note.is_empty() {
                format!("- **{}** _(source: {})_", name, evidence)
            } else {
                format!("- **{}** — {} _(source: {})_", name, note, evidence)
            }
        })
        .collect();

    let workflow = component_workflow_mermaid(architecture);
    let missing_count = stale.get("missingReferences").and_then(Value::as_array).map(|a| a.len()).unwrap_or(0);
    let stale_claims_count = stale.get("staleClaims").and_then(Value::as_array).map(|a| a.len()).unwrap_or(0);

    let classified_flows = architecture.get("flows").and_then(Value::as_array).cloned().unwrap_or_default();
    let mut flow_rows: Vec<String> = Vec::new();
    if classified_flows.is_empty() {
        flow_rows.push("_No classified product flows yet; run Blueprint Phase 2 synthesis._".to_string());
    } else {
        flow_rows.push("| Flow | Status | Evidence | Impact |".to_string());
        flow_rows.push("|---|---|---|---|".to_string());
        for flow in &classified_flows {
            let name = markdown_cell(flow.get("name").or_else(|| flow.get("flow")).and_then(Value::as_str).unwrap_or("Unnamed flow"));
            let status = markdown_cell(flow.get("status").and_then(Value::as_str).unwrap_or("undetermined"));
            let evidence = markdown_cell(flow.get("evidence").and_then(Value::as_str).unwrap_or("Undetermined"));
            let impact = markdown_cell(flow.get("impact").and_then(Value::as_str).unwrap_or(""));
            flow_rows.push(format!("| {} | {} | {} | {} |", name, status, evidence, impact));
        }
    }

    let synthesized_coverage = architecture.get("capabilityCoverage").and_then(Value::as_array).cloned().unwrap_or_default();
    let mut capability_rows: Vec<String> = Vec::new();
    if synthesized_coverage.is_empty() {
        capability_rows.push("| Capability | Status | Evidence |".to_string());
        capability_rows.push("|---|---|---|".to_string());
        capability_rows.push("| document/ADR/plan claims | covered | _source: .agent/map.json:claims_ |".to_string());
        capability_rows.push("| code symbols and relationships | partial until Phase 2 classifies provider coverage | _source: .agent/graph/graph.db_ |".to_string());
        capability_rows.push("| contradiction/staleness arbitration | covered | _source: .agent/stale.json_ |".to_string());
    } else {
        capability_rows.push("| Capability | Status | Evidence | Provider |".to_string());
        capability_rows.push("|---|---|---|---|".to_string());
        for row in &synthesized_coverage {
            let capability = markdown_cell(row.get("capability").or_else(|| row.get("name")).and_then(Value::as_str).unwrap_or("Unnamed capability"));
            let status = markdown_cell(row.get("status").and_then(Value::as_str).unwrap_or("undetermined"));
            let evidence = markdown_cell(row.get("evidence").and_then(Value::as_str).unwrap_or("Undetermined"));
            let provider = markdown_cell(row.get("provider").and_then(Value::as_str).unwrap_or(""));
            capability_rows.push(format!("| {} | {} | {} | {} |", capability, status, evidence, provider));
        }
    }

    let mut lines: Vec<String> = vec![
        header,
        String::new(),
        format!("# {} — Architecture", repo),
        String::new(),
        "Technical overview of components, interfaces, classified flow inventory, and capability coverage.".to_string(),
        "The deterministic Phase-1 graph supplies the evidence substrate; Phase-2 understanding supplies".to_string(),
        "the human component names and operational flow. Raw file and symbol nodes are intentionally omitted.".to_string(),
        String::new(),
    ];
    if let Some(summary) = architecture.get("summary").and_then(Value::as_str) {
        if !summary.is_empty() {
            lines.push(markdown_cell(summary));
            lines.push(String::new());
        }
    }
    lines.push("## System workflow".to_string());
    lines.push(String::new());
    if let Some(w) = &workflow {
        lines.push("```mermaid".to_string());
        lines.push(w.clone());
        lines.push("```".to_string());
        lines.push(String::new());
        lines.push("_(source: .agent/understanding.json:architecture.dataFlow)_".to_string());
    } else {
        lines.push("_No synthesized component workflow yet; run Blueprint Phase 2 synthesis._".to_string());
    }
    lines.push(String::new());
    lines.push("## Components".to_string());
    lines.push(String::new());
    if component_rows.is_empty() {
        lines.push("- _No synthesized components yet; run Blueprint Phase 2 synthesis._".to_string());
    } else {
        lines.extend(component_rows);
    }
    lines.push(String::new());
    lines.push("## Flow inventory".to_string());
    lines.push(String::new());
    lines.extend(flow_rows);
    lines.push(String::new());
    lines.push("## Capability coverage".to_string());
    lines.push(String::new());
    lines.extend(capability_rows);
    lines.push(String::new());
    lines.push("## Health & Security (loud-partial when graph is missing)".to_string());
    lines.push(String::new());
    lines.push(format!("- Stale claims: **{}** _(source: .agent/stale.json:staleClaims)_", stale_claims_count));
    lines.push(format!("- Missing references: **{}** _(source: .agent/stale.json:missingReferences)_", missing_count));
    lines.push("- Detailed health and security findings live in `.agent/understanding.json`; every synthesized".to_string());
    lines.push("  component and flow above retains its recorded evidence. _(source: .agent/understanding.json)_".to_string());
    lines.push(String::new());
    lines.push("## Status".to_string());
    lines.push(String::new());
    lines.push(format!("Generated from index signature `{}`. Unchanged-repo rebuilds are byte-identical.", generation_id));
    lines.push(String::new());

    lines.join("\n")
}

// ── README pointer ─────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ReadmePointerMode {
    Absent,
    Created,
    Updated,
}

/// Mirrors `maintainReadmePointer`.
pub fn maintain_readme_pointer(root: &Path) -> std::io::Result<ReadmePointerMode> {
    let readme_path = root.join("README.md");
    let text = match fs::read_to_string(&readme_path) {
        Ok(t) => t,
        Err(_) => return Ok(ReadmePointerMode::Absent),
    };
    let block = [
        MARKER,
        "## Repository truth docs",
        "- [Product overview](docs/product.md) — what this is and does (generated, code-grounded)",
        "- [Architecture](docs/architecture.md) — components, flows, interfaces (generated, code-grounded)",
        END_MARKER,
    ]
    .join("\n");

    let start_idx = text.find(MARKER);
    let end_idx = start_idx.and_then(|s| text[s..].find(END_MARKER).map(|i| s + i));

    if start_idx.is_none() || end_idx.is_none() {
        let next = if text.ends_with('\n') {
            format!("{}\n{}\n", text, block)
        } else {
            format!("{}\n{}\n", text, block)
        };
        write_text(&readme_path, &next)?;
        return Ok(ReadmePointerMode::Created);
    }

    let start_idx = start_idx.unwrap();
    let end_idx = end_idx.unwrap();
    let before = &text[..start_idx];
    let after_raw = &text[end_idx + END_MARKER.len()..];
    let after = if after_raw.trim().is_empty() {
        "\n".to_string()
    } else if after_raw.starts_with('\n') || after_raw.starts_with("\r\n") {
        after_raw.to_string()
    } else {
        format!("\n{}", after_raw)
    };
    let next = format!("{}{}{}", before, block, after);
    if next != text {
        write_text(&readme_path, &next)?;
    }
    Ok(ReadmePointerMode::Updated)
}

// ── Orchestrator ───────────────────────────────────────────────────────

/// Options for [`generate_docs`], mirroring the JS `opts` object.
#[derive(Debug, Clone, Copy, Default)]
pub struct GenerateDocsOptions {
    pub no_readme_link: bool,
}

/// Outcome of [`generate_docs`], mirroring the JS result object.
#[derive(Debug, Clone, Default)]
pub struct GenerateDocsResult {
    pub mode: &'static str,
    pub conflicts: Vec<String>,
    pub wrote: Vec<String>,
    pub fallback: Vec<String>,
    pub readme: Option<ReadmePointerMode>,
    pub retired: Vec<String>,
}

fn read_json(path: &Path) -> Option<Value> {
    let text = fs::read_to_string(path).ok()?;
    serde_json::from_str(&text).ok()
}

/// Build the small input projection needed by the generated-doc emitter from
/// the native store when legacy `.agent/{map,index,claims,stale}.json` files
/// are absent. Native builds persist one SQLite generation, so requiring the
/// retired JSON artifacts would leave this otherwise production operation
/// permanently in `missing_map` mode.
fn read_native_inputs(root: &Path) -> Option<(Value, Value, Value, Option<Value>, Value)> {
    let db_path = root.join(".agent").join("graph").join("graph.db");
    if !db_path.exists() {
        return None;
    }
    let conn = crate::store::open_store_read_only(&db_path).ok()?;
    let manifest_text: String = conn
        .query_row("SELECT value FROM generation WHERE key = 'manifest'", [], |row| row.get(0))
        .ok()?;
    let manifest: Value = serde_json::from_str(&manifest_text).ok()?;
    let source_signature = manifest.get("sourceHash").and_then(Value::as_str).unwrap_or("");
    let repo_root: String = conn
        .query_row("SELECT value FROM generation WHERE key = 'repoRoot'", [], |row| row.get(0))
        .ok()
        .and_then(|value: String| serde_json::from_str::<Value>(&value).ok())
        .and_then(|value| value.as_str().map(str::to_owned))
        .unwrap_or_else(|| root.to_string_lossy().into_owned());
    let repo = Path::new(&repo_root)
        .file_name()
        .and_then(|value| value.to_str())
        .filter(|value| !value.is_empty())
        .unwrap_or("repository");

    let mut file_statement = conn.prepare("SELECT path FROM files ORDER BY path").ok()?;
    let files: Vec<String> = file_statement
        .query_map([], |row| row.get(0))
        .ok()?
        .collect::<Result<_, _>>()
        .ok()?;
    let docs_count: i64 = conn
        .query_row("SELECT COUNT(*) FROM documents", [], |row| row.get(0))
        .ok()?;
    let claims_count: i64 = conn
        .query_row("SELECT COUNT(*) FROM claims", [], |row| row.get(0))
        .ok()?;
    let code_refs: i64 = conn
        .query_row("SELECT COUNT(*) FROM edges", [], |row| row.get(0))
        .ok()?;
    let mut doc_statement = conn.prepare("SELECT path FROM documents ORDER BY path").ok()?;
    let doc_nodes: Vec<Value> = doc_statement
        .query_map([], |row| row.get::<_, String>(0))
        .ok()?
        .collect::<Result<Vec<_>, _>>()
        .ok()?
        .into_iter()
        .map(|path| json!({"kind": "doc", "path": path}))
        .collect();
    let mut claim_statement = conn.prepare("SELECT status, text, source, line FROM claims ORDER BY rowid").ok()?;
    let claims: Vec<Value> = claim_statement
        .query_map([], |row| {
            Ok(json!({
                "status": row.get::<_, Option<String>>(0)?.unwrap_or_default(),
                "text": row.get::<_, String>(1)?,
                "source": row.get::<_, Option<String>>(2)?.unwrap_or_default(),
                "line": row.get::<_, Option<i64>>(3)?,
            }))
        })
        .ok()?
        .collect::<Result<Vec<_>, _>>()
        .ok()?;
    let map = json!({
        "schemaVersion": 1,
        "repo": repo,
        "stats": {"files": files.len(), "docs": docs_count, "claims": claims_count, "codeRefs": code_refs},
        "nodes": doc_nodes,
    });
    let index = json!({"schemaVersion": 1, "sourceSignature": source_signature, "files": files});
    let stale = json!({"missingReferences": [], "staleClaims": []});
    Some((map, Value::Array(claims), stale, None, index))
}

/// Orchestrate a docs build. Mirrors `generateDocs`. Unlike the legacy
/// module (which throws on malformed `.agent/claims.json` etc. via
/// `JSON.parse`), this treats any unparsable required JSON file the same
/// as a missing one for `map.json` (mirroring `readJson`'s hard throw
/// only for `map.json` reads that DO exist but are malformed would panic
/// in JS too; this port instead resolves to `None` -> `"missing_map"`,
/// which is a strictly safer fail-closed behavior for the same
/// "no map, can't proceed" outcome).
pub fn generate_docs(root: &Path, opts: GenerateDocsOptions) -> std::io::Result<GenerateDocsResult> {
    let map_path = root.join(".agent").join("map.json");
    let (map, claims_raw, stale, understanding_candidate, index) = if map_path.exists() {
        // An explicitly present but malformed legacy map remains fail-closed;
        // do not silently substitute a native projection for corrupt input.
        let Some(map) = read_json(&map_path) else {
            return Ok(GenerateDocsResult { mode: "missing_map", ..Default::default() });
        };
        (
            map,
            read_json(&root.join(".agent").join("claims.json")).unwrap_or_else(|| json!([])),
            read_json(&root.join(".agent").join("stale.json"))
                .unwrap_or_else(|| json!({"missingReferences": [], "staleClaims": []})),
            read_json(&root.join(".agent").join("understanding.json")),
            read_json(&root.join(".agent").join("index.json"))
                .unwrap_or_else(|| json!({"files": [], "sourceSignature": "no-index"})),
        )
    } else {
        match read_native_inputs(root) {
            Some(inputs) => inputs,
            None => return Ok(GenerateDocsResult { mode: "missing_map", ..Default::default() }),
        }
    };

    let graph_manifest = read_stored_manifest(root);
    let graph_generation_id = graph_manifest.as_ref().and_then(|m| m.get("generationId")).and_then(Value::as_str);

    let understanding = match (graph_generation_id, &understanding_candidate) {
        (Some(gid), Some(u)) if u.get("sourceGenerationId").and_then(Value::as_str) == Some(gid) => {
            u.clone()
        }
        _ => json!(null),
    };

    let repo = map.get("repo").and_then(Value::as_str).unwrap_or("").to_string();
    let files: Vec<String> = index
        .get("files")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default()
        .into_iter()
        .filter_map(|entry| match entry {
            Value::String(s) => Some(s),
            Value::Object(ref m) => m.get("path").and_then(Value::as_str).map(|s| s.to_string()),
            _ => None,
        })
        .collect();
    let stats = map.get("stats").cloned().unwrap_or(json!({}));
    let docs_stats = DocsStats {
        files: stats.get("files").and_then(Value::as_i64).unwrap_or(0),
        docs: stats.get("docs").and_then(Value::as_i64).unwrap_or(0),
        claims: stats.get("claims").and_then(Value::as_i64).unwrap_or(0),
        code_refs: stats.get("codeRefs").and_then(Value::as_i64).unwrap_or(0),
    };
    let source_signature = index.get("sourceSignature").and_then(Value::as_str).unwrap_or("");
    let generation_id = generated_docs_generation_id(&files, &docs_stats, source_signature);

    let claims: Vec<DocClaim> = claims_raw
        .as_array()
        .cloned()
        .unwrap_or_default()
        .into_iter()
        .map(|c| DocClaim {
            status: c.get("status").and_then(Value::as_str).unwrap_or("").to_string(),
            text: c.get("text").and_then(Value::as_str).unwrap_or("").to_string(),
            source: c.get("source").and_then(Value::as_str).unwrap_or("").to_string(),
            line: c.get("line").cloned().unwrap_or(Value::Null),
        })
        .collect();

    let product_body = product_sections(&repo, &claims, &map, &generation_id);
    let arch_body = architecture_sections(&repo, &map, &stale, &understanding, &generation_id);

    let target_product = root.join(DOC_PATH_PRODUCT);
    let target_arch = root.join(DOC_PATH_ARCHITECTURE);

    let mut conflicts: Vec<String> = Vec::new();
    if !is_generated(&target_product) {
        conflicts.push(DOC_PATH_PRODUCT.to_string());
    }
    if !is_generated(&target_arch) {
        conflicts.push(DOC_PATH_ARCHITECTURE.to_string());
    }

    let mut result = GenerateDocsResult {
        mode: if conflicts.is_empty() { "wrote" } else { "docs_conflict" },
        conflicts: conflicts.clone(),
        ..Default::default()
    };

    if !conflicts.is_empty() {
        let fallback_dir = root.join(FALLBACK_DIR);
        write_text(&fallback_dir.join("product.md"), &product_body)?;
        write_text(&fallback_dir.join("architecture.md"), &arch_body)?;
        result.fallback = vec![DOC_PATH_PRODUCT.to_string(), DOC_PATH_ARCHITECTURE.to_string()];
        return Ok(result);
    }

    write_text(&target_product, &product_body)?;
    write_text(&target_arch, &arch_body)?;
    result.wrote = vec![DOC_PATH_PRODUCT.to_string(), DOC_PATH_ARCHITECTURE.to_string()];

    if !opts.no_readme_link {
        result.readme = Some(maintain_readme_pointer(root)?);
    }

    let start_here = root.join(START_HERE_PATH);
    if start_here.exists() {
        fs::remove_file(&start_here)?;
        result.retired.push(START_HERE_PATH.to_string());
    }

    Ok(result)
}
