// MBR-1001 — Deterministic renderers for the generated product docs and the
// README link inventory.
//
// docs/product.md, docs/architecture.md, docs/operations.md, and docs/protocol.md
// are DERIVED artifacts: every claim in them (tool count, adapter list, platform
// status) is rendered from the same product truth that
// scripts/tools/productization/generate-product-truth.mjs computes from live source
// (mcp/server.mjs + docs/membrane/capability-matrix.v1.json). Hand-edits are
// overwritten by regeneration; `node scripts/tools/productization/check-docs.mjs --check`
// fails when any of these files is stale or a README link is broken.

/** Word forms the generated docs use for counts. */
const COUNT_WORDS = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve"];

export function countWord(n) {
  return COUNT_WORDS[n] ?? String(n);
}

/** Split capability-matrix support tiers into tier-1 and best-effort platforms. */
export function platformStatus(matrix) {
  const tiers = matrix.support_tiers || {};
  return {
    tier1: tiers.tier_1 || [],
    bestEffort: tiers.tier_2_best_effort || [],
  };
}

const GENERATED_BY =
  "This file is generated by `scripts/tools/productization/generate-product-truth.mjs`.\n" +
  "Do not hand-edit; regenerate instead. `node scripts/tools/productization/check-docs.mjs --check`\n" +
  "fails if this file is stale.";

function toolTable(truth) {
  return truth.tools.map((name) => `| \`${name}\` |`).join("\n");
}

function adapterLines(truth) {
  return truth.adapters.map((name) => `- \`${name}\``).join("\n");
}

function axisTable(truth) {
  return [
    "| Axis | Responsibility |",
    "|---|---|",
    ...truth.axisDefinitions.map(({ label, description }) => `| **${label}** | ${description} |`),
  ];
}


function derivedFromLines(truth) {
  return truth.generatedFrom.map((source) => `- \`${source}\``);
}

/** docs/product.md — what the product is and does, grounded in source truth. */
export function renderProductDoc(truth, platforms) {
  return [
    "# Membrane — product overview (generated)",
    "",
    GENERATED_BY,
    "",
    "Membrane sits between an agent and its sources and returns the smallest useful",
    "set of current code, rules, decisions, and memory for each task — plus a receipt",
    "showing what entered context, what did not, and why. See `README.md` for the",
    "narrative overview; this file carries the source-derived facts.",
    "",
    "## Public surface",
    "",
    `- **MCP server** — ${countWord(truth.toolCount)} tools over stdio:`,
    "",
    toolTable(truth),
    "",
    `- **Client adapters** — ${countWord(truth.adapterCount)} host adapters from the vendored capability matrix:`,
    "",
    adapterLines(truth),
    "",
    "## Six axes",
    "",
    ...axisTable(truth),
    "",
    `Current supported target is **${truth.currentTarget}**. Cortex is **${truth.cortexScope}**; **${truth.residentServiceAuthority === "hub" ? "Membrane Hub" : truth.residentServiceAuthority}** is the sole resident service authority.`,
    "",
    "## Platform status",
    "",
    platformSentence(platforms),
    "",
    "## Derived from",
    "",
    ...derivedFromLines(truth),
    "",
  ].join("\n");
}

/** docs/architecture.md — components, flows, and interfaces at the truth level. */
export function renderArchitectureDoc(truth, platforms) {
  return [
    "# Membrane — architecture (generated)",
    "",
    GENERATED_BY,
    "",
    "Component and interface inventory derived from source. Canonical architecture",
    "lives in `docs/subsystems/MEMBRANE_CANONICAL_ARCHITECTURE_AND_IMPLEMENTATION_DOCTRINE.md` and Blueprint truth semantics live in `docs/subsystems/BLUEPRINT_CANONICAL_SOURCE_OF_TRUTH.md`.",
    "",
    "## Components",
    "",
    "| Component | Source of truth | Role |",
    "|---|---|---|",
    `| MCP server | \`engine/crates/membrane-mcp/\` | ${countWord(truth.toolCount)} native tools over stdio and authenticated Hub loopback transport |`,
    `| Client adapters | \`docs/membrane/capability-matrix.v1.json\` | ${countWord(truth.adapterCount)} host adapters, per-host honest capability levels |`,
    "| Federation gateway | loopback `POST /federate` | parallel provider fan-out behind the context tool |",
    "| Cortex durable memory | `engine/` | governed durable-memory store, lifecycle, and retrieval; no resident service authority |",
    "| Membrane Hub | `apps/membrane-hub/` | sole resident service, process-lifecycle, install, update, and release authority |",
    "| Cross-provider budget | `engine/crates/membrane-core/` | one native attention budget with explicit lanes; every receipt carries a reconciliation |",
    "",
    "## Interfaces",
    "",
    `- \`membrane_context\` and the other ${countWord(truth.toolCount - 1)} MCP tools are the client contract;`,
    "  provider internals never leak into adapters.",
    "- The federation gateway is the only route from tools to memory/recall providers.",
    "- The cross-provider budget (MBR-608) reconciles every receipt's selected",
    "  and delivered tokens under one budget, split into four explicit lanes.",
    "  See [Cross-provider budget model](#cross-provider-budget-model) below.",
    "",
    "## Cross-provider budget model",
    "",
    "The planner fills a single global token ceiling; the renderer emits against",
    "it; the receipt carries the reconciliation. Lanes are the contract surface",
    "that sums to the global total — there is no separate per-provider counter.",
    "",
    "| Lane | When a block lands here | Token consumption |",
    "|---|---|---|",
    "| `native` | Host loaded the content with a matching host receipt (MBR-010) | zero bytes; zero tokens |",
    "| `rendered` | The renderer serialized inline text into the prompt | `renderedTokens` |",
    "| `resolver_backed` | Resolver reference only; the agent retrieves on demand | zero tokens; `deliveredChars` only |",
    "| `metadata_only` | Metadata without content | zero tokens; zero bytes |",
    "",
    "Lanes are mutually exclusive per block. The reconciliation on every",
    "`context.receipt` packet (`packet.reconciliation`) carries the per-lane",
    "totals and the global total, plus a stable alert id on the FIRST failure in",
    "deterministic order:",
    "",
    "- `budget_lane_unclassified` — a block could not be mapped to any lane",
    "  (contract drift; the renderer must stamp `block.lane`).",
    "- `global_ceiling_exceeded` — selected tokens exceed `packet.budget.maxTokens`.",
    "- `selected_without_delivered` — a rendered lane selected more tokens than",
    "  it delivered (visible failure like MBR-011's alert).",
    "",
    "Native source of truth is `engine/crates/membrane-core/src/reconcile.rs`;",
    "the typed contract lives",
    "at `engine/crates/membrane-protocol/src/types.rs` (`BudgetLaneKind`,",
    "`BudgetReconciliationV1`, `BudgetReconciliationRowV1`).",
    "",
    "## Platform status",
    "",
    platformSentence(platforms),
    "",
    "## Derived from",
    "",
    "- `engine/crates/membrane-core/`",
    "- `engine/crates/membrane-protocol/src/types.rs`",
    ...derivedFromLines(truth),
    "",
    "## Process plane separation (MBR-108)",
    "",
    "The membrane executable is partitioned into three process planes. Each plane",
    "owns its own entry point, its own failure domain, and the files it may write.",
    "Adding a fourth plane is a breaking change to the contract.",
    "",
    "| Plane | Owns | Reads from | Writes to |",
    "|---|---|---|---|",
    "| Application | Hub-side CLI/API handling and MCP routing; stateless client transports | Data | — |",
    "| Control | Hub-owned in-process lifecycle, admission, worker supervision, health | Data | Data |",
    "| Data | SQLite catalog, receipts, snapshot manifests, heartbeat rows, installation identity | — | — |",
    "",
    "Rules:",
    "",
    "- The Data plane never owns a network port. A path under `engine/crates/cortex-store/`",
    "  MUST NOT import a transport crate.",
    "- The Control plane never opens SQLite directly. Lease, lockfile, and heartbeat",
    "  writes go through typed Data-plane APIs exposed by Membrane runtime.",
    "- The Application plane never writes to disk except via the Control or Data",
    "  plane. `membrane_runtime::serve` and `membrane_runtime::cli` only emit",
    "  typed receipts; they never call `std::fs` directly outside the receipts",
    "  registry.",
    "",
    "Mode → plane mapping (single source of truth: `membrane::modes::plane_of`):",
    "",
    "- `membrane cli …` → Application",
    "- active Hub runtime request handling → Application",
    "- `membrane stdio-mcp` stateless transport → Application",
    "- Hub in-process lifecycle owner → Control",
    "",
    "The typed contract lives at `engine/crates/membrane-runtime/src/planes.rs`",
    "(`Plane`, `PlaneBoundary`, `PLANE_BOUNDARIES`, `plane_for_path`). The golden",
    "fixture is `schemas/registry/plane-boundaries.v1.golden.json`; the runtime",
    "classifies a source file into a plane by the crate segment that owns it",
    "(`membrane-runtime` / `membrane-mcp` / stateless `membrane` → Application,",
    "Hub supervisor → Control, `cortex-store` → Data). The active Hub hosts all",
    "resident plane work in-process; bounded stateless clients may execute",
    "Application adapters but no plane owns a separate resident process.",
    "",
    "Forbid list (enforced by review at book-end):",
    "",
    "- A pull request that opens SQLite outside the Data plane.",
    "- A pull request that adds a transport crate dependency to the Data plane.",
    "- A pull request that adds a fourth entry to `PLANE_BOUNDARIES` without",
    "  bumping `plane-boundaries.v1.golden.json` to v2.",
    "",
  ].join("\n");
}

function platformSentence(platforms) {
  const tier1 = platforms.tier1.join(" and ");
  const bestEffort = platforms.bestEffort.length
    ? ` ${platforms.bestEffort.join(" and ")} is tier-2 best-effort.`
    : "";
  if (platforms.tier1.length === 1 && platforms.tier1[0] === "Windows" && !platforms.bestEffort.length) {
    return "The sole supported current target is **Windows** (tier 1). Other targets are not current supported targets.";
  }
  return `Supported platforms are **${tier1}** (tier 1).${bestEffort}`;
}

/** docs/operations.md — build, run, and verify the product docs surface. */
export function renderOperationsDoc(truth, platforms) {
  return [
    "# Membrane — operations (generated)",
    "",
    GENERATED_BY,
    "",
    "## Regenerating and checking product truth",
    "",
    "```sh",
    "node scripts/tools/productization/generate-product-truth.mjs           # regenerate all generated docs",
    "node scripts/tools/productization/generate-product-truth.mjs --check   # fail if truth artifacts are stale",
    "node scripts/tools/productization/check-docs.mjs --check               # full gate: links, counts, platform status",
    "```",
    "",
    "The gate fails on a broken README link, a stale generated doc, a wrong claimed",
    `tool count (source truth: ${countWord(truth.toolCount)}), or a stale platform status`,
    `(source truth: ${platforms.tier1.join(" + ")}).`,
    "",
    "## Running the product",
    "",
    "```sh",
    "pnpm install        # Node >= 20, pnpm 11",
    "pnpm test           # MCP server + client + install-binding suites",
    "rightkit cargo build --manifest-path engine/Cargo.toml --workspace  # Cortex engine",
    "rightkit cargo test --manifest-path engine/Cargo.toml --workspace --features fastembed  # with real ONNX embeddings",
    "```",
    "",
    "## Platform status",
    "",
    platformSentence(platforms),
    "",
    // These runbook links used to live only as a hand-edit inside the
    // generated file, so the next regeneration silently deleted them and
    // broke tests/runbook-links/hub-alerts.test.mjs. Emitting them from the
    // generator is what makes them survive -- a generated doc cannot carry
    // hand-maintained content.
    "## Hub alerts & reasons",
    "",
    "Hub is read-only: an alert never authorizes an in-place repair. Use the canonical",
    "[Hub alert runbook](troubleshooting/hub-alerts.md), which maps every stable reason",
    "to its precise entry, smallest safe first action, and repair boundary. Topic runbooks",
    "cover [diagnostics](troubleshooting/diagnostics.md), [backups](troubleshooting/backups.md),",
    "[migrations](troubleshooting/migrations.md), [update rollback](troubleshooting/update-rollback.md),",
    "and [support bundles](troubleshooting/support-bundles.md).",
    "",
  ].join("\n");
}

/** docs/protocol.md — the MCP tool surface contract. */
export function renderProtocolDoc(truth, platforms) {
  return [
    "# Membrane — protocol (generated)",
    "",
    GENERATED_BY,
    "",
    "The MCP server speaks MCP over stdio and serves both the 2025-03-26 and",
    "2026-07-28 MCP discovery eras. Caller authorization is bound to the exact",
    "repository, root, and scope of each request.",
    "",
    `## Tools (${truth.toolCount})`,
    "",
    toolTable(truth),
    "",
    "## Behavioral contract",
    "",
    "- `membrane_context` routes through the loopback `/federate` endpoint, never raw recall.",
    "- Knowledge and feedback proposals require durable persistence with readback;",
    "  unavailable persistence is a tool error unless explicit advisory policy is selected.",
    "- Scratchpads are ephemeral, non-searchable, non-authoritative, and never consolidated.",
    "- Temporal supersession requires an explicit single-valued predicate policy.",
    "- Checkpoints are A0 session orientation state, never durable knowledge.",
    "- Source reads require a hash-bound DocReadV1 reference.",
    "",
    "## Platform status",
    "",
    platformSentence(platforms),
    "",
  ].join("\n");
}

/**
 * Extract local markdown link targets from README text. Returns relative paths
 * only — external URLs, anchors, and mailto links are not filesystem targets.
 */
export function extractLocalLinks(markdownText) {
  const targets = [];
  const pattern = /\[[^\]]*\]\(([^)\s]+)(?:\s+"[^"]*")?\)/g;
  let match;
  while ((match = pattern.exec(markdownText)) !== null) {
    const target = match[1];
    if (/^(https?:|mailto:|#)/.test(target)) continue;
    targets.push(target.split("#")[0]);
  }
  return [...new Set(targets)].sort();
}
