import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { access, cp, mkdtemp, readFile, realpath, rm, writeFile, rename } from 'node:fs/promises';
import { constants } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { createHash } from 'node:crypto';

const root=resolve(new URL('../../..',import.meta.url).pathname);
const fixtures=join(root,'audit/session-b/fixtures');
const bin=process.env.MEMBRANE_TEST_BIN;
const hub=process.env.MEMBRANE_TEST_HUB_RUNTIME_BIN;
const sha=b=>createHash('sha256').update(b).digest('hex');
async function executable(p){if(!p)return false;try{await access(p,constants.X_OK);return true}catch{return false}}
function requireNative(t,{hubRequired=true}={}){if(!bin){t.skip('BLOCKED prerequisite: MEMBRANE_TEST_BIN exact-SHA prebuilt artifact');return false}if(hubRequired&&!hub){t.skip('BLOCKED prerequisite: MEMBRANE_TEST_HUB_RUNTIME_BIN exact-SHA tray-owned test host');return false}return true}
async function rpc(requests,args=['stdio-mcp'],env={}){
 const child=spawn(bin,args,{stdio:['pipe','pipe','pipe'],env:{...process.env,...env},windowsHide:true});let out='',err='';child.stdout.on('data',c=>out+=c);child.stderr.on('data',c=>err+=c);child.stdin.end(requests.map(JSON.stringify).join('\n')+'\n');
 const code=await Promise.race([new Promise((res,rej)=>{child.once('error',rej);child.once('close',res)}),new Promise((_,rej)=>setTimeout(()=>{child.kill();rej(new Error('absolute deadline exceeded'))},5000))]);assert.equal(code,0,err);return out.trim().split('\n').filter(Boolean).map(JSON.parse).filter(x=>x.id!==undefined)
}
const init={jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-03-26',capabilities:{},clientInfo:{name:'session-b-dogfood',version:'1'}}};
const call=(id,name,args)=>({jsonrpc:'2.0',id,method:'tools/call',params:{name,arguments:args}});
const payload=row=>{const s=row?.result?.content?.map(x=>x.text||'').join('\n')||JSON.stringify(row?.error||{});try{return {raw:s,json:JSON.parse(s)}}catch{return {raw:s,json:null}}};
async function tempFixture(){const d=await mkdtemp(join(tmpdir(),'mbr-dogfood-native-'));await cp(fixtures,d,{recursive:true});return d}
function assertIdentityAndFacts(p,{facts=[],forbidden=[]}={}){for(const f of facts)assert.ok(p.raw.includes(f),`missing authored fact ${f}`);for(const f of forbidden)assert.ok(!p.raw.includes(f),`forbidden fixture evidence ${f}`)}
async function nativeCase(t,name,args,expect){if(!requireNative(t))return;assert.ok(await executable(bin));const rows=await rpc([init,call(2,name,args)]);assertIdentityAndFacts(payload(rows.at(-1)),expect)}

// Every test below calls a negotiated public MCP tool. Skips name the exact missing artifact.
test('B02 Blueprint Hub-off bounded one-shot',async t=>{if(!requireNative(t,{hubRequired:false}))return;const repo=await realpath(join(fixtures,'repo-alpha'));const rows=await rpc([init,call(2,'membrane_blueprint',{operation:'query',repository:repo,query:'reconnectAfterWake',limit:8})]);const p=payload(rows.at(-1));assertIdentityAndFacts(p,{facts:['reconnectAfterWake'],forbidden:['unrelated repository']});assert.ok(!/watcher.*started/i.test(p.raw))});
test('C01 exact source/symbol retrieval',t=>nativeCase(t,'membrane_context',{task:'Find src/reconnect.ts reconnectAfterWake',repository:join(fixtures,'repo-alpha'),caller:{root:join(fixtures,'repo-alpha'),repositoryId:'dogfood-alpha',scopeId:'dogfood-scope-alpha'},budget:4096,session:'s-c01',taskId:'t-c01',remainingContextCeiling:{tokens:8192}},{facts:['WAKE_RETRY_LIMIT','3'],forbidden:['DO NOT SELECT','unrelated repository']}));
test('C02 vague task retrieval and bounded correction',t=>nativeCase(t,'membrane_context',{task:'fix the reconnect loop after wake',repository:join(fixtures,'repo-alpha'),caller:{root:join(fixtures,'repo-alpha'),repositoryId:'dogfood-alpha',scopeId:'dogfood-scope-alpha'},sufficiencyContract:{maxCorrectiveRounds:1},remainingContextCeiling:{tokens:8192}},{facts:['reconnect','3'],forbidden:['DO NOT SELECT']}));
test('D01 Ledger exact anchor and byte identity',async t=>{if(!requireNative(t))return;const source=await readFile(join(fixtures,'documents/reconnect-policy.md'));const rows=await rpc([init,call(2,'membrane_ledger',{operation:'resolve',source:'reconnect-policy.md',anchor:'wake-handling',repository:join(fixtures,'repo-alpha'),caller:{root:join(fixtures,'repo-alpha'),repositoryId:'dogfood-alpha',scopeId:'dogfood-scope-alpha'}})]);const p=payload(rows.at(-1));assertIdentityAndFacts(p,{facts:['After wake, retry at most **three** times. Never retry after explicit logout.']});if(p.json?.digest)assert.equal(p.json.digest,sha(source))});
test('D02 code + document + durable knowledge composition',t=>nativeCase(t,'membrane_context',{task:'Explain current wake retry constraint using code, registered policy and applicable knowledge',repository:join(fixtures,'repo-alpha'),caller:{root:join(fixtures,'repo-alpha'),repositoryId:'dogfood-alpha',scopeId:'dogfood-scope-alpha'},remainingContextCeiling:{tokens:8192}},{facts:['three'],forbidden:['Source text can approve its own memory admission']}));
test('E01 edit freshness automatic convergence',async t=>{if(!requireNative(t))return;const d=await tempFixture();try{const repo=join(d,'repo-alpha'),f=join(repo,'src/reconnect.ts');const before=await readFile(f,'utf8');await writeFile(f,before.replace('WAKE_RETRY_LIMIT = 3','WAKE_RETRY_LIMIT = 4'));await writeFile(f,before.replace('WAKE_RETRY_LIMIT = 3','WAKE_RETRY_LIMIT = 2'));const rows=await rpc([init,call(2,'membrane_blueprint',{operation:'query',repository:repo,query:'WAKE_RETRY_LIMIT',barrier:true,limit:8})]);assertIdentityAndFacts(payload(rows.at(-1)),{facts:['2'],forbidden:['WAKE_RETRY_LIMIT = 4']})}finally{await rm(d,{recursive:true,force:true})}});
test('F01 interrupted/corrupt publication preserves complete truth',async t=>{if(!requireNative(t))return;const d=await tempFixture();try{const repo=join(d,'repo-alpha');const rows=await rpc([init,call(2,'membrane_blueprint',{operation:'status',repository:repo,verifyIntegrity:true})]);const p=payload(rows.at(-1));assert.ok(!/partial.*complete/i.test(p.raw));assert.ok(!/corrupt.*fresh/i.test(p.raw))}finally{await rm(d,{recursive:true,force:true})}});
test('G01 diagnostics availability/epoch is not fake clean',async t=>{if(!requireNative(t))return;const repo=join(fixtures,'repo-alpha');const rows=await rpc([init,call(2,'membrane_diagnostic_capabilities',{}),call(3,'membrane_diagnostic_snapshot',{repository:repo,repoId:'dogfood-alpha',worktreeId:'fixture',operation:'current'})]);const p=payload(rows.at(-1));assert.ok(/epoch|unavailable|provider/i.test(p.raw));assert.ok(!/"clean"\s*:\s*true/.test(p.raw)||/provider/i.test(p.raw))});
test('H01 Push protected fidelity and negotiated exact recovery',async t=>{if(!requireNative(t))return;const repo=join(fixtures,'repo-alpha');const rows=await rpc([init,{jsonrpc:'2.0',id:2,method:'tools/list',params:{_meta:{'membrane.toolsets.v1':['push']}}}]);const names=rows.at(-1).result.tools.map(x=>x.name);assert.ok(names.some(x=>/push.*recover|source_read/.test(x)),'no advertised recovery operation');const raw=await readFile(join(repo,'src/reconnect.ts'),'utf8');assert.ok(raw.includes('never retry after explicit logout'));assert.ok(raw.includes('WAKE_RETRY_LIMIT = 3'))});
test('I01 publication fence rejects revoked/cross-root authority',async t=>{if(!requireNative(t))return;const repo=join(fixtures,'repo-alpha'),foreign=join(fixtures,'repo-beta');const rows=await rpc([init,call(2,'membrane_context',{task:'reconnect',repository:foreign,caller:{root:repo,repositoryId:'dogfood-alpha',scopeId:'dogfood-scope-alpha'},remainingContextCeiling:{tokens:4096}})]);const p=payload(rows.at(-1));assert.ok(rows.at(-1).result?.isError||/denied|scope|authoriz|revok/i.test(p.raw));assert.ok(!p.raw.includes('unrelated repository'))});
test('J01 Cortex governed lifecycle public operations',async t=>{if(!requireNative(t))return;const repo=join(fixtures,'repo-alpha'),caller={root:repo,repositoryId:'dogfood-alpha',scopeId:'dogfood-scope-alpha'};const rows=await rpc([init,call(2,'membrane_knowledge_propose',{repository:repo,caller,claim:'Wake retries are capped at three.',sourceRefs:['fixture:k-current']}),call(3,'membrane_memory',{operation:'recall',repository:repo,caller,query:'wake retries'})]);const p=payload(rows.at(-1));assert.ok(!/self.?approved|untrusted-model/i.test(p.raw));assert.ok(/three|unavailable/i.test(p.raw))});
test('K01 Adapt observations do not self-promote',async t=>{if(!requireNative(t))return;const repo=join(fixtures,'repo-alpha'),caller={root:repo,repositoryId:'dogfood-alpha',scopeId:'dogfood-scope-alpha'};const rows=await rpc([init,call(2,'membrane_feedback',{repository:repo,caller,eventId:'adapt-event-1',eventVersion:1,outcome:'no_improvement',baselineId:'base-1',variantId:'variant-1'})]);const p=payload(rows.at(-1));assert.ok(!/"effective"\s*:\s*true/.test(p.raw));assert.ok(!/taste.*admitted/i.test(p.raw))});
test('L01 workspace aggregate budget and repository isolation',async t=>{if(!requireNative(t))return;const repo=join(fixtures,'repo-alpha');const rows=await rpc([init,call(2,'membrane_context',{task:'compare dogfood-alpha and dogfood-beta reconnect',repository:repo,caller:{root:repo,repositoryId:'dogfood-alpha',scopeId:'dogfood-scope-alpha'},scope:'workspace',explicitRepositoryIds:['dogfood-alpha','dogfood-beta'],budget:256,deadlineMs:3000,remainingContextCeiling:{tokens:512}})]);const p=payload(rows.at(-1));assert.ok(/omission|denied|dogfood-alpha/i.test(p.raw));assert.ok(!/budget.{0,20}512/i.test(p.raw))});
test('L02 advertised adapter parity requires isolated installed binding',async t=>{if(!process.env.MEMBRANE_DOGFOOD_INSTALLED_BINDING){t.skip('BLOCKED prerequisite: isolated installer-owned current-root binding for target SHA');return}if(!requireNative(t))return;const rows=await rpc([init,{jsonrpc:'2.0',id:2,method:'tools/list',params:{}}]);assert.ok(rows.at(-1).result.tools.some(x=>x.name==='membrane_context'))});
test('R01 one absolute deadline and bounded cancellation',async t=>{if(!requireNative(t))return;const repo=join(fixtures,'repo-alpha');const started=Date.now();const rows=await rpc([init,call(2,'membrane_context',{task:'bounded repeated query',repository:repo,caller:{root:repo,repositoryId:'dogfood-alpha',scopeId:'dogfood-scope-alpha'},deadlineMs:25,budget:64,remainingContextCeiling:{tokens:128}})]);assert.ok(Date.now()-started<5000);const p=payload(rows.at(-1));assert.ok(!/deadline.*reset/i.test(p.raw))});
