"""adapt — mine durable working preferences from local session transcripts into MemRight.

Usage (from workspace root):
  py -3.11 tools/pipelines/memory/adapt/adapt.py --smoke --lane local    # 3-session dry run
  py -3.11 tools/pipelines/memory/adapt/adapt.py --backfill --dry-run    # preview everything
  py -3.11 tools/pipelines/memory/adapt/adapt.py --backfill --apply --first-run-ok
  py -3.11 tools/pipelines/memory/adapt/adapt.py --incremental --apply --limit 20

Stages: discover -> extract (LLM) -> synthesize (LLM) -> apply (memright put + digest + audit).
State/rules/digest live in ~/.claude/adapt/ (machine-local, disposable).
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import subprocess
import sys
import tempfile
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import adapt_llm  # noqa: E402
import adapt_sessions as ts  # noqa: E402

RULES_FILE = ts.STATE_DIR / "rules.json"
AUDIT_FILE = ts.STATE_DIR / "audit.jsonl"
DIGEST_FILE = ts.STATE_DIR / "adapt-digest.md"


def _run_memright(args: list[str]) -> bool:
    """Invoke the installed memright shim (never touches tokens). Fail closed with the error."""
    try:
        res = subprocess.run(["memright", *args], capture_output=True, text=True, timeout=30)
    except (OSError, subprocess.TimeoutExpired) as exc:
        print(f"error: memright shim failed: {exc}", file=sys.stderr)
        return False
    if res.returncode != 0:
        print(f"error: memright {args[0]} rc={res.returncode}: {res.stderr.strip()}",
              file=sys.stderr)
        return False
    return True


def preflight_apply(lane: str, allow_external: bool) -> bool:
    if not ts.scanner_available():
        print("error: adapt apply requires detect-secrets or gitleaks before transcript text can leave the machine",
              file=sys.stderr)
        return False
    if lane != "local" and not allow_external:
        print("error: external LLM lanes require --allow-external-lane", file=sys.stderr)
        return False
    if not adapt_llm.lane_available(lane):
        print(f"error: LLM lane unavailable: {lane}", file=sys.stderr)
        return False
    if not _run_memright(["--help"]):
        print("error: memright shim is unavailable; run setup-workspace.py first", file=sys.stderr)
        return False
    return True


def initialized(state: dict) -> bool:
    return bool(state.get("initialized_at"))


def rule_body(rule: dict, evidence: str, tool: str) -> str:
    today = dt.date.today().isoformat()
    return (
        f"**[adapt/{rule['category']}]** — {rule['rule']} "
        f"Confidence: {rule['confidence']:.2f} "
        f"(observations: {rule['observations']}, needs_review: {str(rule.get('needs_review', False)).lower()}, "
        f"updated {today})\n"
        f"**Why:** mined from {tool or 'session'} prompts; e.g. \"{evidence}\"\n"
        f"**How to apply:** treat as a standing preference whenever the matching work comes up.\n"
    )


def load_rules() -> dict:
    try:
        return json.loads(RULES_FILE.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def save_rules(rules: dict) -> None:
    ts.STATE_DIR.mkdir(parents=True, exist_ok=True)
    RULES_FILE.write_text(json.dumps(rules, indent=2), encoding="utf-8")


def write_digest(rules: dict, path: Path) -> None:
    by_cat: dict[str, list[dict]] = defaultdict(list)
    for r in rules.values():
        by_cat[r["category"]].append(r)
    lines = ["# Adapt digest (generated by adapt; MemRight rows are the source of truth)", ""]
    for cat in sorted(by_cat):
        lines.append(f"# {cat}")
        for r in sorted(by_cat[cat], key=lambda x: -x["confidence"]):
            lines.append(f"- {r['rule']} Confidence: {r['confidence']:.2f}")
        lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def write_metrics(metrics: dict, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(metrics, indent=2), encoding="utf-8")


def _audit(entry: dict) -> None:
    ts.STATE_DIR.mkdir(parents=True, exist_ok=True)
    with open(AUDIT_FILE, "a", encoding="utf-8") as fh:
        fh.write(json.dumps({"ts": dt.datetime.now(dt.timezone.utc).isoformat(), **entry}) + "\n")


def _scope_for(obs_list: list[dict]) -> str:
    scopes = {o.get("scope") for o in obs_list if o.get("scope")}
    return scopes.pop() if len(scopes) == 1 else "D--Claude"


def apply_actions(actions: list[dict], obs_by_cat: dict, rules: dict,
                  out_dir: Path, dry_run: bool) -> tuple[int, bool]:
    changed = 0
    ok_all = True
    for act in actions:
        name, kind = act["name"], act["action"]
        if kind == "keep":
            continue
        obs_list = obs_by_cat.get(act["category"], [])
        evidence = obs_list[0]["evidence"] if obs_list else ""
        tool = obs_list[0].get("tool", "") if obs_list else ""
        scope = rules.get(name, {}).get("scope") or _scope_for(obs_list)
        record = {"name": name, "category": act["category"], "rule": act["rule"],
                  "confidence": act["confidence"], "observations": act.get("observations", 1),
                  "scope": scope, "needs_review": act.get("needs_review", False)}
        print(f"  {kind:6s} {name}  conf={act['confidence']:.2f}  [{scope}]")
        if dry_run:
            continue
        body = rule_body(record, evidence, tool)
        with tempfile.NamedTemporaryFile("w", suffix=".md", delete=False,
                                         encoding="utf-8", dir=str(out_dir)) as tmp:
            tmp.write(body)
            tmp_path = tmp.name
        ok = _run_memright(["put", name, "--scope", scope, "--file", tmp_path])
        Path(tmp_path).unlink(missing_ok=True)
        if ok:
            rules[name] = record
            _audit({"action": kind, **record})
            changed += 1
        else:
            ok_all = False
            _audit({"event": "memright_write_failed", "action": kind, "name": name, "scope": scope})
    return changed, ok_all


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--backfill", action="store_true", help="process all unlearned sessions")
    mode.add_argument("--incremental", action="store_true", help="only new/modified sessions")
    mode.add_argument("--smoke", action="store_true", help="3 most recent sessions, forced dry-run")
    ap.add_argument("--apply", action="store_true", help="write to MemRight (default: dry-run)")
    ap.add_argument("--dry-run", action="store_true", help="explicit no-write preview")
    ap.add_argument("--limit", type=int, default=None, help="max sessions this run")
    ap.add_argument("--lane", default="local", choices=("local", "minimax"), help="LLM lane")
    ap.add_argument("--allow-external-lane", action="store_true",
                    help="allow sending redacted transcript text to an external LLM lane")
    ap.add_argument("--first-run-ok", action="store_true",
                    help="allow the first state-initializing apply/backfill")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    dry_run = args.dry_run or args.smoke or not args.apply
    limit = 3 if args.smoke else args.limit

    state = ts.load_state()
    if args.apply and not preflight_apply(args.lane, args.allow_external_lane):
        return 2
    if args.apply and not initialized(state) and not (args.smoke or args.first_run_ok):
        print("error: first adapt apply requires --first-run-ok after smoke/dry-run review",
              file=sys.stderr)
        return 2
    sessions = ts.new_sessions(state, limit=limit)
    if args.smoke:
        sessions = sessions[-3:]
    if not sessions:
        if not args.quiet:
            print("adapt: no new sessions")
        ts.save_state(state)   # persists excluded/empty markings
        return 0
    print(f"adapt: {len(sessions)} sessions "
          f"({sum(len(s.turns) for s in sessions)} turns), dry_run={dry_run}")
    drops = sum(s.stats.dropped_turns for s in sessions)
    trunc = sum(s.stats.truncated_turns for s in sessions)
    scans = sum(s.stats.scanner_drops for s in sessions)
    print(f"adapt: parser stats dropped={drops} truncated={trunc} scanner_drops={scans}")

    turns = [(s.tool, t.scope, t.text) for s in sessions for t in s.turns]
    observations: list[dict] = []
    for i, batch in enumerate(adapt_llm.build_batches(turns), 1):
        if not args.quiet:
            print(f"  extract batch {i}: {len(batch)} turns")
        observations.extend(adapt_llm.extract_observations(batch, lane=args.lane))
    print(f"adapt: {len(observations)} candidate observations")

    rules = load_rules()
    obs_by_cat: dict[str, list[dict]] = defaultdict(list)
    for o in observations:
        obs_by_cat[o["category"]].append(o)

    changed = 0
    ok_all = True
    for cat, obs in sorted(obs_by_cat.items()):
        existing = [r for r in rules.values() if r["category"] == cat]
        actions = adapt_llm.synthesize(cat, existing, obs, lane=args.lane)
        delta, ok = apply_actions(actions, obs_by_cat, rules, ts.STATE_DIR, dry_run)
        changed += delta
        ok_all = ok_all and ok

    if not dry_run:
        if not ok_all:
            print("error: one or more MemRight writes failed; state not advanced", file=sys.stderr)
            return 1
        save_rules(rules)
        write_digest(rules, DIGEST_FILE)
        ts.mark_learned(state, sessions)
        state["initialized_at"] = state.get("initialized_at") or dt.datetime.now(dt.timezone.utc).isoformat()
        ts.save_state(state)
        print(f"adapt: applied {changed} rule changes; digest at {DIGEST_FILE}")
    else:
        print("adapt: dry run — nothing written; re-run with --apply")
    return 0


if __name__ == "__main__":
    sys.exit(main())
