export default {
  schema: 1,
  kind: "headless-addon",
  addon: "membrane",
  version: "0.1.1",
  packageManager: "pnpm",
  distribution: { provider: "github-releases", repository: "Orthic-Labs/Membrane" },
  checks: ["test", "test:all"],
  buildInputs: {
    include: [
      "right-addon.config.mjs", "package.json", "pnpm-lock.yaml",
      "scripts/release/stage-addon-binaries.mjs",
      "engine/Cargo.toml", "engine/Cargo.lock", "engine/crates/**",
      "dist/install/assets/membrane-tab-icon.png",
      "LICENSE", "docs/legal/EULA.txt", "docs/legal/PRIVACY.md", "docs/legal/THIRD-PARTY-NOTICES.txt",
    ],
    exclude: ["**/target/**", "**/tests/**"],
  },
  consumer: {
    contract: "orthic-product-v1",
    productId: "membrane",
    displayName: "Membrane",
    hubCompatRange: ">=0.1.11 <0.2.0",
    commandRole: "command",
    serviceRole: "service",
    iconRole: "icon",
    serviceStop: ["SIGTERM"],
    statusEndpoint: {
      host: "127.0.0.1",
      port: 47851,
      authHeader: "Authorization",
      tokenRelativePath: "tools/.cache/memory/api-token",
    },
  },
  targets: {
    mac: {
      targetTriple: "aarch64-apple-darwin",
      files: [
        { role: "command", name: "membrane", source: "engine/target/aarch64-apple-darwin/release/membrane", executable: true },
        { role: "service", name: "crypt-service", source: "engine/target/aarch64-apple-darwin/release/crypt-service", executable: true },
        { role: "icon", name: "membrane-tab-icon.png", source: "dist/install/assets/membrane-tab-icon.png" },
        { role: "license", name: "LICENSE", source: "LICENSE" },
        { role: "eula", name: "EULA.txt", source: "docs/legal/EULA.txt" },
        { role: "privacy", name: "PRIVACY.md", source: "docs/legal/PRIVACY.md" },
        { role: "third-party-notices", name: "THIRD-PARTY-NOTICES.txt", source: "docs/legal/THIRD-PARTY-NOTICES.txt" },
      ],
      build: {
        cmd: "node",
        args: ["scripts/release/stage-addon-binaries.mjs", "build", "--manifest-path", "engine/Cargo.toml", "--workspace", "--locked", "--release", "--target", "aarch64-apple-darwin", "-p", "membrane", "--bin", "membrane", "-p", "crypt", "--bin", "crypt-service", "--", "membrane", "crypt-service"],
      },
      signing: { contract: "apple-developer-id-executable-v1", teamId: "6KLGD3LLKF" },
    },
    win: {
      targetTriple: "x86_64-pc-windows-msvc",
      files: [
        { role: "command", name: "membrane.exe", source: "engine/target/x86_64-pc-windows-msvc/release/membrane.exe", executable: true },
        { role: "service", name: "crypt-service.exe", source: "engine/target/x86_64-pc-windows-msvc/release/crypt-service.exe", executable: true },
        { role: "icon", name: "membrane-tab-icon.png", source: "dist/install/assets/membrane-tab-icon.png" },
        { role: "license", name: "LICENSE", source: "LICENSE" },
        { role: "eula", name: "EULA.txt", source: "docs/legal/EULA.txt" },
        { role: "privacy", name: "PRIVACY.md", source: "docs/legal/PRIVACY.md" },
        { role: "third-party-notices", name: "THIRD-PARTY-NOTICES.txt", source: "docs/legal/THIRD-PARTY-NOTICES.txt" },
      ],
      build: {
        cmd: "node",
        args: ["scripts/release/stage-addon-binaries.mjs", "build", "--manifest-path", "engine/Cargo.toml", "--workspace", "--locked", "--release", "--target", "x86_64-pc-windows-msvc", "-p", "membrane", "--bin", "membrane", "-p", "crypt", "--bin", "crypt-service", "--", "membrane.exe", "crypt-service.exe"],
      },
      signing: { contract: "azure-artifact-signing-v1" },
    },
  },
};
