// tests/generated-docs.test.mjs — Cortex B6.5 acceptance tests
//
// Covers plan §12a / B6.5.4:
//   1. fixture repo build emits both docs with generation headers + provenance
//   2. unchanged rebuild is byte-identical
//   3. README marker block is created once, updated in place, content untouched
//   4. hand-written unmarked docs/product.md triggers docs_conflict + .agent/docs/ fallback
//   5. contradicted claims do not appear as facts in either doc
//   6. generated docs are excluded from the next build's discovery and signature
//
// (START-HERE retirement is covered in standalone-completion.test.mjs; the
// skill no longer writes START-HERE.md at all, so a "delete after write" test
// would be testing the wrong contract.)

import { test } from "node:test";
import assert from "node:assert/strict";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import { readEnvelope } from "./_store-helpers.mjs";

import {
  DOC_PATHS,
  generateDocs,
  isGenerated,
  maintainReadmePointer,
} from "../lib/generated-docs.mjs";

// Use a self-contained CLI invocation so we exercise the real build path.
const SCRIPT = fileURLToPath(new URL("../scripts/cortex.mjs", import.meta.url));

function makeFixture(name = null) {
  const unique = `cortex-b65-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const root = name ? join(tmpdir(), unique, name) : join(tmpdir(), unique);
  mkdirSync(root, { recursive: true });
  mkdirSync(join(root, "src"), { recursive: true });
  writeFileSync(
    join(root, "README.md"),
    "# Fixture\n\nA small fixture for B6.5 tests.\n",
  );
  writeFileSync(
    join(root, "AGENTS.md"),
    "# Agents\n\n- The product handles transcription.\n- Local-first is implemented.\n",
  );
  writeFileSync(join(root, "src/index.ts"), "// hello\nexport const x = 1;\n");
  return root;
}

const it = (name, fn) => test(name, async () => fn());

it("B6.5.4 fixture build emits both docs with generation headers + provenance", async () => {
  const root = makeFixture();
  try {
    const { execFileSync } = await import("node:child_process");
    execFileSync("node", [SCRIPT, "build", "--out", ".agent"], {
      cwd: root,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
    const productPath = join(root, DOC_PATHS.product);
    const archPath = join(root, DOC_PATHS.architecture);
    assert.ok(existsSync(productPath), `expected ${DOC_PATHS.product} to exist`);
    assert.ok(existsSync(archPath), `expected ${DOC_PATHS.architecture} to exist`);
    const product = readFileSync(productPath, "utf8");
    const arch = readFileSync(archPath, "utf8");
    assert.ok(product.startsWith("<!-- generated by cortex"), "product.md missing generation header");
    assert.ok(arch.startsWith("<!-- generated by cortex"), "architecture.md missing generation header");
    assert.ok(product.includes("source: "), "product.md missing provenance markers");
    assert.ok(arch.includes("source: "), "architecture.md missing provenance markers");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

it("generated doc identity is stable across LF and CRLF checkouts", async () => {
  const lfRoot = makeFixture("cortex");
  const crlfRoot = makeFixture("Cortex");
  try {
    for (const name of ["README.md", "AGENTS.md"]) {
      const target = join(crlfRoot, name);
      writeFileSync(target, readFileSync(target, "utf8").replace(/\n/g, "\r\n"));
    }
    const { execFileSync } = await import("node:child_process");
    for (const root of [lfRoot, crlfRoot]) {
      execFileSync("node", [SCRIPT, "build", "--out", ".agent"], {
        cwd: root,
        encoding: "utf8",
        stdio: ["ignore", "pipe", "pipe"],
      });
    }
    const readProductHeader = (root) => readFileSync(join(root, DOC_PATHS.product), "utf8").split(/\r?\n/, 1)[0];
    assert.equal(readProductHeader(crlfRoot), readProductHeader(lfRoot));
  } finally {
    rmSync(lfRoot, { recursive: true, force: true });
    rmSync(crlfRoot, { recursive: true, force: true });
  }
});

it("architecture.md renders the synthesized component workflow as Mermaid", async () => {
  const root = makeFixture();
  try {
    const { execFileSync } = await import("node:child_process");
    execFileSync("node", [SCRIPT, "build", "--out", ".agent"], {
      cwd: root,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
    const sourceGenerationId = readEnvelope(root).generationId;
    writeFileSync(
      join(root, ".agent/understanding.json"),
      `${JSON.stringify({
        sourceGenerationId,
        architecture: {
          summary: "A desktop shell sends dictation work to a resident engine.",
          components: [
            { name: "Tauri shell", evidence: "src-tauri/src/lib.rs:20", note: "Owns desktop state and IPC." },
            { name: "Engine sidecar", evidence: "engine/src/main.rs:12", note: "Owns recording and transcription." },
            { name: "ASR", evidence: "engine/src/asr.rs:44", note: "Decodes conditioned audio." },
          ],
          dataFlow: ["User hotkey -> Tauri shell -> Engine sidecar -> ASR -> Delivery"],
          flows: [
            {
              name: "Hotkey to delivered transcript",
              status: "covered",
              evidence: "src-tauri/src/lib.rs:20 -> engine/src/asr.rs:44",
              impact: "Primary dictation path.",
            },
          ],
        },
      }, null, 2)}\n`,
    );

    generateDocs(root);
    const arch = readFileSync(join(root, DOC_PATHS.architecture), "utf8");
    const mermaid = arch.match(/```mermaid\n([\s\S]*?)\n```/)?.[1] ?? "";

    assert.ok(arch.includes("## System workflow"), "architecture.md missing workflow section");
    assert.match(mermaid, /^flowchart LR/);
    assert.match(mermaid, /\["User hotkey"\]/);
    assert.match(mermaid, /\["Tauri shell"\]/);
    assert.match(mermaid, /\["Engine sidecar"\]/);
    assert.match(mermaid, /\["ASR"\]/);
    assert.match(mermaid, /\["Delivery"\]/);
    assert.match(mermaid, /c0 --> c1/);
    assert.ok(!/code_ref|symbol:|\.agent\/map\.json/.test(mermaid), "workflow leaked raw graph nodes");
    assert.ok(arch.includes("src-tauri/src/lib.rs:20"), "component evidence missing");
    assert.ok(arch.includes("Hotkey to delivered transcript"), "classified flow missing");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

it("architecture.md rejects understanding from a different graph generation", async () => {
  const root = makeFixture();
  try {
    const { execFileSync } = await import("node:child_process");
    execFileSync("node", [SCRIPT, "build", "--out", ".agent"], {
      cwd: root,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "pipe"],
    });
    writeFileSync(
      join(root, ".agent/understanding.json"),
      `${JSON.stringify({
        sourceGenerationId: "xxh128:stale-generation",
        architecture: {
          components: [{ name: "Stale component", evidence: "old.rs:1" }],
          dataFlow: ["Stale input -> Stale component -> Stale output"],
        },
      }, null, 2)}\n`,
    );

    generateDocs(root);
    const arch = readFileSync(join(root, DOC_PATHS.architecture), "utf8");

    assert.ok(!arch.includes("```mermaid"), "stale understanding produced a Mermaid diagram");
    assert.ok(!arch.includes("Stale component"), "stale understanding leaked into components");
    assert.ok(arch.includes("No synthesized component workflow yet"), "fresh synthesis guidance missing");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

it("B6.5.4 unchanged rebuild is byte-identical", async () => {
  const root = makeFixture();
  try {
    const { execFileSync } = await import("node:child_process");
    const cwd = root;
    execFileSync("node", [SCRIPT, "build", "--out", ".agent"], { cwd, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
    const first = readFileSync(join(root, DOC_PATHS.product), "utf8");
    const firstArch = readFileSync(join(root, DOC_PATHS.architecture), "utf8");
    execFileSync("node", [SCRIPT, "build", "--out", ".agent"], { cwd, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
    const second = readFileSync(join(root, DOC_PATHS.product), "utf8");
    const secondArch = readFileSync(join(root, DOC_PATHS.architecture), "utf8");
    assert.equal(first, second, "product.md not byte-identical across unchanged rebuilds");
    assert.equal(firstArch, secondArch, "architecture.md not byte-identical across unchanged rebuilds");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

it("B6.5.4 README marker block is created and updated in place; outside content untouched", async () => {
  const root = makeFixture();
  try {
    const { execFileSync } = await import("node:child_process");
    execFileSync("node", [SCRIPT, "build", "--out", ".agent"], { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
    const readmePath = join(root, "README.md");
    const after = readFileSync(readmePath, "utf8");
    assert.ok(after.includes("<!-- cortex:docs:start -->"), "README missing pointer block");
    assert.ok(after.includes("<!-- cortex:docs:end -->"), "README missing end marker");
    // Outside content preserved
    assert.ok(after.startsWith("# Fixture\n"), "README header content altered");
    assert.ok(after.includes("A small fixture for B6.5 tests."), "README body content altered");
    // Re-running build leaves the block idempotent
    execFileSync("node", [SCRIPT, "build", "--out", ".agent"], { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
    const after2 = readFileSync(readmePath, "utf8");
    assert.equal(after, after2, "README pointer block not idempotent");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

it("B6.5.4 hand-written unmarked docs/architecture.md triggers docs_conflict + .agent/docs/ fallback", async () => {
  const root = makeFixture();
  try {
    // Plant a hand-written architecture.md BEFORE running build.
    const handWritten = "# Architecture (mine)\n\nI wrote this myself, do not clobber.\n";
    mkdirSync(join(root, "docs"), { recursive: true });
    writeFileSync(join(root, DOC_PATHS.architecture), handWritten);
    const { execFileSync } = await import("node:child_process");
    execFileSync("node", [SCRIPT, "build", "--out", ".agent"], { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
    const result = generateDocs(root);
    assert.equal(result.mode, "docs_conflict", "expected docs_conflict mode");
    assert.ok(result.conflicts.includes(DOC_PATHS.architecture), "architecture.md should be in conflicts list");
    const fallbackArch = join(root, ".agent/docs/architecture.md");
    assert.ok(existsSync(fallbackArch), "fallback .agent/docs/architecture.md should exist");
    assert.ok(fallbackArch.startsWith, "fallback path is a string");
    // The hand-written file must be untouched
    const after = readFileSync(join(root, DOC_PATHS.architecture), "utf8");
    assert.equal(after, handWritten, "hand-written architecture.md was clobbered");
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

it("B6.5.4 contradicted claims do not appear as facts in either doc", async () => {
  const root = makeFixture();
  try {
    // Add a doc with a contradicted-style claim
    writeFileSync(
      join(root, "CONTRADICTED.md"),
      "# Contradicted\n\n- This feature is implemented and shipped.\n- This contradicts reality.\n",
    );
    const { execFileSync } = await import("node:child_process");
    execFileSync("node", [SCRIPT, "build", "--out", ".agent"], { cwd: root, encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
    const product = readFileSync(join(root, DOC_PATHS.product), "utf8");
    const arch = readFileSync(join(root, DOC_PATHS.architecture), "utf8");
    // The classifyStatus heuristic tags "contradicts" as stale; stale claims are excluded from product.md.
    // Verify the contradicted claim text doesn't appear as a capability row.
    const contradictedLine = "This contradicts reality.";
    // We don't forbid the literal phrase (it could appear in stale reporting), but we forbid it
    // appearing as a "capability" / feature statement — those are filtered to implemented/partial/claim.
    // The product doc is allowed to mention stale items only inside "Honesty / Gaps", never as a capability.
    const productLines = product.split("\n");
    const capabilitySection = productLines.slice(
      productLines.findIndex((l) => l.includes("## Capabilities")),
      productLines.findIndex((l) => l.includes("## Entry points")),
    );
    assert.ok(
      !capabilitySection.some((l) => l.includes(contradictedLine)),
      "contradicted claim leaked into product.md Capabilities",
    );
    assert.ok(
      !arch.includes("This feature is implemented and shipped"),
      "implemented-and-shipped claim from contradicted doc leaked into architecture.md as fact",
    );
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});

it("isGenerated returns true for missing files and marker-prefixed files", () => {
  const fakePath = join(tmpdir(), `nonexistent-${Date.now()}.md`);
  assert.equal(isGenerated(fakePath), true, "missing path should be considered generated");
  const tmp = join(tmpdir(), `marker-${Date.now()}.md`);
  writeFileSync(tmp, "<!-- generated by cortex x gen:y -->\n\n# body\n");
  try {
    assert.equal(isGenerated(tmp), true, "marker-prefixed file should be considered generated");
    writeFileSync(tmp, "# I wrote this by hand\n");
    assert.equal(isGenerated(tmp), false, "hand-written file should not be considered generated");
  } finally {
    rmSync(tmp, { force: true });
  }
});

it("maintainReadmePointer skips silently when no README present", () => {
  const root = join(tmpdir(), `noreadme-${Date.now()}`);
  mkdirSync(root, { recursive: true });
  try {
    const result = maintainReadmePointer(root);
    assert.equal(result.mode, "readme_absent");
    assert.equal(existsSync(join(root, "README.md")), false);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
