// MBR-1001 — Deterministic renderers for the generated product docs and the
// README link inventory.
//
// docs/product.md, docs/architecture.md, docs/operations.md, and docs/protocol.md
// are DERIVED artifacts: every claim in them (tool count, adapter list, platform
// status) is rendered from the same product truth that
// tools/productization/generate-product-truth.mjs computes from live source
// (mcp/server.mjs + docs/membrane/capability-matrix.v1.json). Hand-edits are
// overwritten by regeneration; `node tools/productization/check-docs.mjs --check`
// fails when any of these files is stale or a README link is broken.

/** Word forms the generated docs use for counts. */
const COUNT_WORDS = ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve"];

export function countWord(n) {
  return COUNT_WORDS[n] ?? String(n);
}

/** Split capability-matrix support tiers into tier-1 and best-effort platforms. */
export function platformStatus(matrix) {
  const tiers = matrix.support_tiers || {};
  return {
    tier1: tiers.tier_1 || [],
    bestEffort: tiers.tier_2_best_effort || [],
  };
}

const GENERATED_BY =
  "This file is generated by `tools/productization/generate-product-truth.mjs`.\n" +
  "Do not hand-edit; regenerate instead. `node tools/productization/check-docs.mjs --check`\n" +
  "fails if this file is stale.";

function toolTable(truth) {
  return truth.tools.map((name) => `| \`${name}\` |`).join("\n");
}

function adapterLines(truth) {
  return truth.adapters.map((name) => `- \`${name}\``).join("\n");
}


function derivedFromLines(truth) {
  return truth.generatedFrom.map((source) => `- \`${source}\``);
}

/** docs/product.md — what the product is and does, grounded in source truth. */
export function renderProductDoc(truth, platforms) {
  return [
    "# Membrane — product overview (generated)",
    "",
    GENERATED_BY,
    "",
    "Membrane sits between an agent and its sources and returns the smallest useful",
    "set of current code, rules, decisions, and memory for each task — plus a receipt",
    "showing what entered context, what did not, and why. See `README.md` for the",
    "narrative overview; this file carries the source-derived facts.",
    "",
    "## Public surface",
    "",
    `- **MCP server** — ${countWord(truth.toolCount)} tools over stdio:`,
    "",
    toolTable(truth),
    "",
    `- **Client adapters** — ${countWord(truth.adapterCount)} host adapters from the vendored capability matrix:`,
    "",
    adapterLines(truth),
    "",
    "## Platform status",
    "",
    platformSentence(platforms),
    "",
    "## Derived from",
    "",
    ...derivedFromLines(truth),
    "",
  ].join("\n");
}

/** docs/architecture.md — components, flows, and interfaces at the truth level. */
export function renderArchitectureDoc(truth, platforms) {
  return [
    "# Membrane — architecture (generated)",
    "",
    GENERATED_BY,
    "",
    "Component and interface inventory derived from source. Detailed design history",
    "lives in `docs/UNIFIED-CONTEXT-SYSTEM-ARCHITECTURE.md` and `docs/MEMBRANE-ADR-INDEX.md`.",
    "",
    "## Components",
    "",
    "| Component | Source of truth | Role |",
    "|---|---|---|",
    `| MCP server | \`mcp/server.mjs\` | ${countWord(truth.toolCount)} tools over stdio; dual-era MCP discovery |`,
    `| Client adapters | \`docs/membrane/capability-matrix.v1.json\` | ${countWord(truth.adapterCount)} host adapters, per-host honest capability levels |`,
    "| Federation gateway | loopback `POST /federate` | parallel provider fan-out behind the context tool |",
    "| Crypt engine | `engine/` | durable memory: Rust CLI plus loopback service over SQLite |",
    "",
    "## Interfaces",
    "",
    `- \`membrane_context\` and the other ${countWord(truth.toolCount - 1)} MCP tools are the client contract;`,
    "  provider internals never leak into adapters.",
    "- The federation gateway is the only route from tools to memory/recall providers.",
    "",
    "## Platform status",
    "",
    platformSentence(platforms),
    "",
    "## Derived from",
    "",
    ...derivedFromLines(truth),
    "",
  ].join("\n");
}

function platformSentence(platforms) {
  const tier1 = platforms.tier1.join(" and ");
  const bestEffort = platforms.bestEffort.length
    ? ` ${platforms.bestEffort.join(" and ")} is tier-2 best-effort.`
    : "";
  return `Supported platforms are **${tier1}** (tier 1).${bestEffort}`;
}

/** docs/operations.md — build, run, and verify the product docs surface. */
export function renderOperationsDoc(truth, platforms) {
  return [
    "# Membrane — operations (generated)",
    "",
    GENERATED_BY,
    "",
    "## Regenerating and checking product truth",
    "",
    "```sh",
    "node tools/productization/generate-product-truth.mjs           # regenerate all generated docs",
    "node tools/productization/generate-product-truth.mjs --check   # fail if truth artifacts are stale",
    "node tools/productization/check-docs.mjs --check               # full gate: links, counts, platform status",
    "```",
    "",
    "The gate fails on a broken README link, a stale generated doc, a wrong claimed",
    `tool count (source truth: ${countWord(truth.toolCount)}), or a stale platform status`,
    `(source truth: ${platforms.tier1.join(" + ")}).`,
    "",
    "## Running the product",
    "",
    "```sh",
    "pnpm install        # Node >= 20, pnpm 11",
    "pnpm test           # MCP server + client + install-binding suites",
    "cargo build --workspace                          # Crypt engine",
    "cargo test --workspace --features fastembed      # with real ONNX embeddings",
    "```",
    "",
    "## Platform status",
    "",
    platformSentence(platforms),
    "",
  ].join("\n");
}

/** docs/protocol.md — the MCP tool surface contract. */
export function renderProtocolDoc(truth, platforms) {
  return [
    "# Membrane — protocol (generated)",
    "",
    GENERATED_BY,
    "",
    "The MCP server speaks MCP over stdio and serves both the 2025-03-26 and",
    "2026-07-28 MCP discovery eras. Caller authorization is bound to the exact",
    "repository, root, and scope of each request.",
    "",
    `## Tools (${truth.toolCount})`,
    "",
    toolTable(truth),
    "",
    "## Behavioral contract",
    "",
    "- `membrane_context` routes through the loopback `/federate` endpoint, never raw recall.",
    "- Knowledge and feedback proposals require durable persistence with readback;",
    "  unavailable persistence is a tool error unless explicit advisory policy is selected.",
    "- Scratchpads are ephemeral, non-searchable, non-authoritative, and never consolidated.",
    "- Temporal supersession requires an explicit single-valued predicate policy.",
    "- Checkpoints are A0 session orientation state, never durable knowledge.",
    "- Source reads require a hash-bound DocReadV1 reference.",
    "",
    "## Platform status",
    "",
    platformSentence(platforms),
    "",
  ].join("\n");
}

/**
 * Extract local markdown link targets from README text. Returns relative paths
 * only — external URLs, anchors, and mailto links are not filesystem targets.
 */
export function extractLocalLinks(markdownText) {
  const targets = [];
  const pattern = /\[[^\]]*\]\(([^)\s]+)(?:\s+"[^"]*")?\)/g;
  let match;
  while ((match = pattern.exec(markdownText)) !== null) {
    const target = match[1];
    if (/^(https?:|mailto:|#)/.test(target)) continue;
    targets.push(target.split("#")[0]);
  }
  return [...new Set(targets)].sort();
}

