import { createHash } from "node:crypto";
import { execFileSync, spawnSync } from "node:child_process";
import { chmodSync, copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { engineReleaseIdentity } from "./release-identity.mjs";
import { resolveManagedCargoTarget } from "./lib/target-root.mjs";

const APP="membrane-hub",VERSION="0.1.10",NAMES=["crypt","crypt-service","membrane"];
const ROLE={crypt:"cli","crypt-service":"service",membrane:"hubCommand"};
const TARGET={mac:"aarch64-apple-darwin",win:"x86_64-pc-windows-msvc"},HOST={mac:"darwin-arm64",win:"win32-x64"};
const KEYS=["commit","dirty","fileCount","sourceTreePath","sourceTreeSha256","releaseGeneration"];
const GENERATED=["apps/membrane-hub/dist","apps/membrane-hub/src-tauri/binaries","apps/membrane-hub/src-tauri/target","apps/membrane-hub/src-tauri/gen","engine/target","apps/membrane-hub/node_modules","tools/.cache"];
export const SIDECAR_NAMES=[...NAMES],REQUIRED_IDENTITY_KEYS=[...KEYS];
export const sha256OfFile=(path)=>createHash("sha256").update(readFileSync(path)).digest("hex");
export const targetTriple=(platform)=>TARGET[platform];
export const unsignedDir=(root)=>join(root,"unsigned");
export const signedDir=(root)=>join(root,"signed");
export const sourceIdentityPath=(root)=>join(root,"source-identity.json");
export const assetsJsonPath=(root)=>join(root,"assets.json");
export const sidecarSourcePath=(hub,target,name)=>join(hub,"src-tauri","binaries",`${name}-${target}${target.includes("windows")?".exe":""}`);
const canonical=(target,name)=>`${name}-${target}${target.includes("windows")?".exe":""}`;
const unsigned=(target,name)=>`${canonical(target,name)}.unsigned`;
export function parseArgs(argv){const [cmd,...args]=argv.slice(2);if(!["prepare","finalize","check-built","check-packaged"].includes(cmd))throw Error("usage: release-assets.mjs <prepare|finalize|check-built|check-packaged> --platform <mac|win>");if(args.length!==2||args[0]!=="--platform"||!TARGET[args[1]])throw Error("--platform must be mac or win");if(cmd==="check-packaged"&&args[1]!=="mac")throw Error("check-packaged only supports mac");return {subcommand:cmd,platform:args[1]};}
export function strictIdentity(raw){const value=JSON.parse(raw),keys=Object.keys(value).sort();if(JSON.stringify(keys)!==JSON.stringify([...KEYS].sort()))throw Error("identity has unexpected keys");if(!/^[0-9a-f]{40}$/i.test(value.commit)||value.dirty!==false||!Number.isSafeInteger(value.fileCount)||value.fileCount<0||value.sourceTreePath!=="engine"||!/^[0-9a-f]{64}$/i.test(value.sourceTreeSha256)||value.releaseGeneration!==`sha256:${value.sourceTreeSha256}`)throw Error("invalid clean release identity");return value;}
function git(root,args,encoding="utf8"){return execFileSync("git",["-C",root,...args],{encoding}).trim();}
export function repoRootFromCwd(cwd){return git(cwd,["rev-parse","--show-toplevel"]);}
export function parentWorkspaceRoot(root){const parent=dirname(root),name=basename(root),row=git(parent,["ls-files","--stage",name]);if(!existsSync(join(parent,".git"))||!row.startsWith("160000 "))throw Error("parent lacks membrane gitlink");return parent;}
export function bundleRoot(parent,commit,platform){return join(parent,"tools",".cache","releases",APP,VERSION,commit,TARGET[platform]);}
function host(platform){if(`${process.platform}-${process.arch}`!==HOST[platform])throw Error(`platform ${platform} requires host ${HOST[platform]}`);}
function clean(root){const rows=git(root,["status","--porcelain","--untracked-files=all"]).split("\n").filter(Boolean);if(rows.some((row)=>!GENERATED.some((p)=>{const path=row.slice(3).trim();return path===p||path.startsWith(`${p}/`);})))throw Error("workspace is not clean");}
function identity(root){const value=engineReleaseIdentity(root);return strictIdentity(JSON.stringify(value));}
function descriptor(root){if(!existsSync(sourceIdentityPath(root)))throw Error("missing source identity");const value=JSON.parse(readFileSync(sourceIdentityPath(root),"utf8"));if(value.app!==APP||value.version!==VERSION||!TARGET[value.platform]||value.target!==TARGET[value.platform])throw Error("invalid source descriptor");value.identity=strictIdentity(JSON.stringify(value.identity));return value;}
function receipt(root){if(!existsSync(assetsJsonPath(root)))throw Error("missing finalized receipt");const value=JSON.parse(readFileSync(assetsJsonPath(root),"utf8"));if(JSON.stringify(Object.keys(value).sort())!==JSON.stringify(["app","files","identity","platform","schemaVersion","target","version"])||value.schemaVersion!==1||value.app!==APP||value.version!==VERSION||value.target!==TARGET[value.platform])throw Error("invalid finalized receipt");value.identity=strictIdentity(JSON.stringify(value.identity));for(const role of Object.values(ROLE)){const file=value.files?.[role];if(!file?.name||!/^[0-9a-f]{64}$/.test(file.sha256))throw Error(`invalid receipt file ${role}`);}return value;}
function buildInfo(path){const result=spawnSync(path,["build-info"],{encoding:"utf8"});if(result.error||result.signal||result.status!==0)throw Error("crypt build-info failed");return JSON.parse(result.stdout);}
export function verifyAuthenticode(verifier,path,run=spawnSync){const result=run(process.execPath,[verifier,"--verify-only",path]);if(result.error||result.signal||result.status!==0)throw Error("Authenticode verify failed");}
function matchInfo(path,id,target){const info=buildInfo(path);if(info.crypt_source_commit!==id.commit||info.source_tree_sha256!==id.sourceTreeSha256||info.release_generation!==id.releaseGeneration||info.target!==target)throw Error("crypt build-info mismatch");}
function signing(path){let result=spawnSync("codesign",["--verify","--strict","--verbose=2",path],{encoding:"utf8"});if(result.error||result.signal||result.status!==0)throw Error(`codesign verify failed: ${path}`);result=spawnSync("codesign",["-dvvv",path],{encoding:"utf8"});const text=`${result.stdout||""}${result.stderr||""}`,team=text.match(/TeamIdentifier=([A-Z0-9]+)/)?.[1];if(result.error||result.signal||result.status!==0||!team)throw Error(`codesign details failed: ${path}`);return {team,sha256:sha256OfFile(path)};}
export function prepareBundle({repoRoot,hubDir,platform}){host(platform);const id=identity(repoRoot);clean(repoRoot);const root=bundleRoot(parentWorkspaceRoot(repoRoot),id.commit,platform),target=TARGET[platform],files={};rmSync(root,{recursive:true,force:true});mkdirSync(unsignedDir(root),{recursive:true});mkdirSync(signedDir(root),{recursive:true});for(const name of NAMES){const from=sidecarSourcePath(hubDir,target,name),to=join(unsignedDir(root),unsigned(target,name));if(!existsSync(from))throw Error(`unsigned sidecar missing: ${from}`);copyFileSync(from,to);chmodSync(to,0o755);files[ROLE[name]]={name:unsigned(target,name),sha256:sha256OfFile(to)};}writeFileSync(sourceIdentityPath(root),`${JSON.stringify({schemaVersion:1,app:APP,version:VERSION,platform,target,identity:id,files})}\n`);return {root,identity:id};}
export function checkBuilt({repoRoot,hubDir,platform}){host(platform);const id=identity(repoRoot),root=bundleRoot(parentWorkspaceRoot(repoRoot),id.commit,platform),source=descriptor(root);if(JSON.stringify(source.identity)!==JSON.stringify(id))throw Error("source identity mismatch");for(const name of NAMES){const path=sidecarSourcePath(hubDir,TARGET[platform],name),file=source.files[ROLE[name]];if(!existsSync(path))throw Error(`regenerated sidecar missing: ${path}`);if(sha256OfFile(path)!==file.sha256)throw Error("regenerated sidecar sha256 mismatch");}return {root,identity:id};}
export function finalizeMac({repoRoot,platform,appMacosDir}){host(platform);const id=identity(repoRoot),root=bundleRoot(parentWorkspaceRoot(repoRoot),id.commit,platform),source=descriptor(root),files={},teams=new Set();for(const name of NAMES){const from=join(appMacosDir,name),to=join(signedDir(root),canonical(TARGET[platform],name));if(!existsSync(from))throw Error(`packaged binary missing: ${from}`);copyFileSync(from,to);chmodSync(to,0o755);const info=signing(to);teams.add(info.team);files[ROLE[name]]={name:canonical(TARGET[platform],name),sha256:info.sha256,signature:"developer-id",team:info.team};}if(teams.size!==1)throw Error("inconsistent TeamIdentifier");matchInfo(join(appMacosDir,"crypt"),id,TARGET[platform]);const value={schemaVersion:1,app:APP,version:VERSION,platform,target:TARGET[platform],identity:id,files};writeFileSync(assetsJsonPath(root),`${JSON.stringify(value)}\n`);return value;}
export function finalizeWin({repoRoot,platform,verifier}){host(platform);const id=identity(repoRoot),root=bundleRoot(parentWorkspaceRoot(repoRoot),id.commit,platform),files={},signed=signedDir(root);descriptor(root);for(const name of NAMES){const path=join(signed,canonical(TARGET[platform],name));if(!existsSync(path))throw Error(`signed staging missing: ${path}`);verifyAuthenticode(verifier,path);files[ROLE[name]]={name:canonical(TARGET[platform],name),sha256:sha256OfFile(path),signature:"authenticode"};}matchInfo(join(signed,canonical(TARGET[platform],"crypt")),id,TARGET[platform]);const value={schemaVersion:1,app:APP,version:VERSION,platform,target:TARGET[platform],identity:id,files};writeFileSync(assetsJsonPath(root),`${JSON.stringify(value)}\n`);return value;}
export function checkPackagedMac({repoRoot,platform,appMacosDir}){host(platform);const id=identity(repoRoot),root=bundleRoot(parentWorkspaceRoot(repoRoot),id.commit,platform),value=receipt(root),teams=new Set();if(JSON.stringify(value.identity)!==JSON.stringify(id))throw Error("final receipt identity mismatch");for(const name of NAMES){const path=join(appMacosDir,name),file=value.files[ROLE[name]],info=signing(path);if(file.signature!=="developer-id"||file.sha256!==info.sha256||file.team!==info.team)throw Error(`packaged ${name} differs from finalized receipt`);teams.add(info.team);}if(teams.size!==1)throw Error("packaged TeamIdentifier mismatch");matchInfo(join(appMacosDir,"crypt"),id,TARGET[platform]);return value;}
export function main(argv){const {subcommand,platform}=parseArgs(argv),repoRoot=repoRootFromCwd(process.cwd()),hubDir=process.cwd();if(subcommand==="prepare")return prepareBundle({repoRoot,hubDir,platform});if(subcommand==="check-built")return checkBuilt({repoRoot,hubDir,platform});if(subcommand==="finalize"){if(platform==="mac")return finalizeMac({repoRoot,platform,appMacosDir:join(resolveManagedCargoTarget(join(hubDir,"src-tauri","Cargo.toml")),"release/bundle/macos/Membrane Hub.app/Contents/MacOS")});return finalizeWin({repoRoot,platform,verifier:fileURLToPath(import.meta.resolve("@rightkit/release/sign-windows.mjs"))});}return checkPackagedMac({repoRoot,platform,appMacosDir:join(resolveManagedCargoTarget(join(hubDir,"src-tauri","Cargo.toml")),"release/bundle/macos/Membrane Hub.app/Contents/MacOS")});}
if(fileURLToPath(import.meta.url)===resolve(process.argv[1]||""))main(process.argv);
