import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { DEFAULT_LOCKFILES, generateSbom, parseCargoLock, parsePnpmLock, SCHEMA } from "./sbom.mjs";

const REPO_ROOT = resolve(fileURLToPath(import.meta.url), "../../../..");

test("generateSbom against this repo's real membrane-hub lockfiles produces only resolved, hash-bound components and no gaps", () => {
  const sbom = generateSbom({ repoRoot: REPO_ROOT });
  assert.equal(sbom.schema, SCHEMA);
  assert.equal(sbom.generatedFrom.length, DEFAULT_LOCKFILES.length);
  assert.ok(sbom.componentCount > 400, `expected >400 real components from the hub's lockfiles, got ${sbom.componentCount}`);
  assert.equal(sbom.components.length, sbom.componentCount);
  assert.deepEqual(sbom.gaps, [], "every real membrane-hub lockfile entry today has a full resolution/checksum; a non-empty gaps array here means a real entry lost its checksum");
  for (const component of sbom.components) {
    assert.match(component.name, /\S/);
    assert.match(component.version, /\S/);
    assert.ok(component.ecosystem === "npm" || component.ecosystem === "cargo");
    if (component.local) {
      assert.equal(component.checksum, null);
      assert.equal(component.source, "local-path");
    } else {
      assert.ok(component.checksum && typeof component.checksum.value === "string" && component.checksum.value.length > 0);
    }
  }
  // membrane-updater is the real path dependency this SBOM must surface as
  // local, not silently drop or fabricate a registry checksum for.
  const updater = sbom.components.find((c) => c.name === "membrane-updater");
  assert.ok(updater, "membrane-updater path dependency must appear in the cargo component list");
  assert.equal(updater.local, true);
});

test("generateSbom is deterministic and hash-binds the exact lockfile bytes it read", () => {
  const first = generateSbom({ repoRoot: REPO_ROOT });
  const second = generateSbom({ repoRoot: REPO_ROOT });
  assert.deepEqual(first, second);
  for (const entry of first.generatedFrom) assert.match(entry.sha256, /^[0-9a-f]{64}$/);
});

test("generateSbom fails closed on a missing lockfile instead of silently skipping it", () => {
  assert.throws(
    () => generateSbom({ repoRoot: REPO_ROOT, lockfiles: [{ ecosystem: "npm", path: "does/not/exist.yaml" }] }),
    /FAIL CLOSED: lockfile not found/,
  );
});

test("parsePnpmLock resolves a normal entry and reports a gap for one with no resolution", () => {
  const text = [
    "packages:",
    "",
    "  left-pad@1.3.0:",
    "    resolution: {integrity: sha512-abc123==}",
    "",
    "  '@scope/pkg@2.0.0':",
    "    resolution: {integrity: sha512-def456==}",
    "    engines: {node: '>=20'}",
    "",
    "  local-thing@0.0.0:",
    "    dev: true",
    "",
    "snapshots:",
    "",
    "  left-pad@1.3.0: {}",
  ].join("\n");
  const { components, gaps } = parsePnpmLock(text, "fixture/pnpm-lock.yaml");
  assert.equal(components.length, 2);
  assert.deepEqual(components[0], { name: "left-pad", version: "1.3.0", ecosystem: "npm", source: "https://registry.npmjs.org/", checksum: { algorithm: "integrity", value: "sha512-abc123==" }, lockfile: "fixture/pnpm-lock.yaml", resolved: true });
  assert.equal(components[1].name, "@scope/pkg");
  assert.equal(gaps.length, 1);
  assert.equal(gaps[0].name, "local-thing");
  assert.match(gaps[0].reason, /no resolution\/integrity recorded/);
});

test("parsePnpmLock returns nothing when there is no packages: section", () => {
  assert.deepEqual(parsePnpmLock("importers:\n  .:\n    dependencies: {}\n", "x.yaml"), { components: [], gaps: [] });
});

test("parseCargoLock resolves a registry crate, records a local path member honestly, and gaps a checksum-less registry source", () => {
  const text = [
    "# This file is automatically @generated by Cargo.",
    "version = 4",
    "",
    "[[package]]",
    'name = "serde"',
    'version = "1.0.0"',
    'source = "registry+https://github.com/rust-lang/crates.io-index"',
    `checksum = "${"a".repeat(64)}"`,
    "",
    "[[package]]",
    'name = "membrane-updater"',
    'version = "0.1.0"',
    "dependencies = [",
    ' "serde",',
    "]",
    "",
    "[[package]]",
    'name = "git-dep"',
    'version = "0.0.1"',
    'source = "git+https://example.invalid/repo#deadbeef"',
  ].join("\n");
  const { components, gaps } = parseCargoLock(text, "fixture/Cargo.lock");
  assert.equal(components.length, 2);
  assert.deepEqual(components[0], { name: "serde", version: "1.0.0", ecosystem: "cargo", source: "registry+https://github.com/rust-lang/crates.io-index", checksum: { algorithm: "sha256", value: "a".repeat(64) }, lockfile: "fixture/Cargo.lock", resolved: true });
  assert.deepEqual(components[1], { name: "membrane-updater", version: "0.1.0", ecosystem: "cargo", source: "local-path", checksum: null, lockfile: "fixture/Cargo.lock", resolved: true, local: true });
  assert.equal(gaps.length, 1);
  assert.equal(gaps[0].name, "git-dep");
  assert.match(gaps[0].reason, /no checksum/);
});

test("a generated SBOM round-trips through JSON to a temp file unchanged", () => {
  const dir = mkdtempSync(join(tmpdir(), "membrane-sbom-cli-"));
  try {
    const outPath = join(dir, "sbom.json");
    const sbom = generateSbom({ repoRoot: REPO_ROOT });
    writeFileSync(outPath, `${JSON.stringify(sbom, null, 2)}\n`);
    const reread = JSON.parse(readFileSync(outPath, "utf8"));
    assert.deepEqual(reread, sbom);
    assert.equal(reread.schema, SCHEMA);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});
