import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { DEFAULT_LOCKFILES, generateSbom, parseCargoLock, parsePnpmLock, SCHEMA } from "./sbom.mjs";

const REPO_ROOT = resolve(fileURLToPath(import.meta.url), "../../../..");
const FIXTURE_ARTIFACT = "scripts/release/evidence/sbom.mjs";

test("generateSbom against this repo's real add-on lockfiles produces only resolved, hash-bound components and no gaps", () => {
  const sbom = generateSbom({ repoRoot: REPO_ROOT, artifact: FIXTURE_ARTIFACT });
  assert.equal(sbom.schema, SCHEMA);
  assert.equal(sbom.artifact.path, FIXTURE_ARTIFACT);
  assert.equal(sbom.artifact.size, readFileSync(resolve(REPO_ROOT, FIXTURE_ARTIFACT)).length);
  assert.equal(sbom.artifact.sha256, createHash("sha256").update(readFileSync(resolve(REPO_ROOT, FIXTURE_ARTIFACT))).digest("hex"));
  assert.equal(sbom.generatedFrom.length, DEFAULT_LOCKFILES.length);
  assert.ok(sbom.componentCount > 100, `expected >100 real components from the add-on lockfiles, got ${sbom.componentCount}`);
  assert.equal(sbom.components.length, sbom.componentCount);
  assert.deepEqual(sbom.gaps, [], "every real add-on lockfile entry today has a full resolution/checksum; a non-empty gaps array here means a real entry lost its checksum");
  for (const component of sbom.components) {
    assert.match(component.name, /\S/);
    assert.match(component.version, /\S/);
    assert.ok(component.ecosystem === "npm" || component.ecosystem === "cargo");
    if (component.local) {
      assert.equal(component.checksum, null);
      assert.equal(component.source, "local-path");
    } else {
      assert.ok(component.checksum && typeof component.checksum.value === "string" && component.checksum.value.length > 0);
    }
  }
  // membrane is a real path dependency this SBOM must surface as
  // local, not silently drop or fabricate a registry checksum for.
  const membrane = sbom.components.find((c) => c.name === "membrane");
  assert.ok(membrane, "membrane path dependency must appear in the cargo component list");
  assert.equal(membrane.local, true);
});

test("generateSbom is deterministic and hash-binds the exact lockfile bytes it read", () => {
  const first = generateSbom({ repoRoot: REPO_ROOT, artifact: FIXTURE_ARTIFACT });
  const second = generateSbom({ repoRoot: REPO_ROOT, artifact: FIXTURE_ARTIFACT });
  assert.deepEqual(first, second);
  for (const entry of first.generatedFrom) assert.match(entry.sha256, /^[0-9a-f]{64}$/);
});

test("generateSbom fails closed on a missing lockfile instead of silently skipping it", () => {
  assert.throws(
    () => generateSbom({ repoRoot: REPO_ROOT, artifact: FIXTURE_ARTIFACT, lockfiles: [{ ecosystem: "npm", path: "does/not/exist.yaml" }] }),
    /FAIL CLOSED: lockfile not found/,
  );
});

test("parsePnpmLock resolves a normal entry and reports a gap for one with no resolution", () => {
  const text = [
    "packages:",
    "",
    "  left-pad@1.3.0:",
    "    resolution: {integrity: sha512-abc123==}",
    "",
    "  '@scope/pkg@2.0.0':",
    "    resolution: {integrity: sha512-def456==}",
    "    engines: {node: '>=20'}",
    "",
    "  local-thing@0.0.0:",
    "    dev: true",
    "",
    "snapshots:",
    "",
    "  left-pad@1.3.0: {}",
  ].join("\n");
  const { components, gaps } = parsePnpmLock(text, "fixture/pnpm-lock.yaml");
  assert.equal(components.length, 2);
  assert.deepEqual(components[0], { name: "left-pad", version: "1.3.0", ecosystem: "npm", source: "https://registry.npmjs.org/", checksum: { algorithm: "integrity", value: "sha512-abc123==" }, lockfile: "fixture/pnpm-lock.yaml", resolved: true });
  assert.equal(components[1].name, "@scope/pkg");
  assert.equal(gaps.length, 1);
  assert.equal(gaps[0].name, "local-thing");
  assert.match(gaps[0].reason, /no resolution\/integrity recorded/);
});

test("parsePnpmLock returns nothing when there is no packages: section", () => {
  assert.deepEqual(parsePnpmLock("importers:\n  .:\n    dependencies: {}\n", "x.yaml"), { components: [], gaps: [] });
});

test("parseCargoLock resolves a registry crate, records a local path member honestly, and gaps a checksum-less registry source", () => {
  const text = [
    "# This file is automatically @generated by Cargo.",
    "version = 4",
    "",
    "[[package]]",
    'name = "serde"',
    'version = "1.0.0"',
    'source = "registry+https://github.com/rust-lang/crates.io-index"',
    `checksum = "${"a".repeat(64)}"`,
    "",
    "[[package]]",
    'name = "membrane-updater"',
    'version = "0.1.0"',
    "dependencies = [",
    ' "serde",',
    "]",
    "",
    "[[package]]",
    'name = "git-dep"',
    'version = "0.0.1"',
    'source = "git+https://example.invalid/repo#deadbeef"',
  ].join("\n");
  const { components, gaps } = parseCargoLock(text, "fixture/Cargo.lock");
  assert.equal(components.length, 2);
  assert.deepEqual(components[0], { name: "serde", version: "1.0.0", ecosystem: "cargo", source: "registry+https://github.com/rust-lang/crates.io-index", checksum: { algorithm: "sha256", value: "a".repeat(64) }, lockfile: "fixture/Cargo.lock", resolved: true });
  assert.deepEqual(components[1], { name: "membrane-updater", version: "0.1.0", ecosystem: "cargo", source: "local-path", checksum: null, lockfile: "fixture/Cargo.lock", resolved: true, local: true });
  assert.equal(gaps.length, 1);
  assert.equal(gaps[0].name, "git-dep");
  assert.match(gaps[0].reason, /no checksum/);
});

test("a generated SBOM round-trips through JSON to a temp file unchanged", () => {
  const dir = mkdtempSync(join(tmpdir(), "membrane-sbom-cli-"));
  try {
    const outPath = join(dir, "sbom.json");
    const sbom = generateSbom({ repoRoot: REPO_ROOT, artifact: FIXTURE_ARTIFACT });
    writeFileSync(outPath, `${JSON.stringify(sbom, null, 2)}\n`);
    const reread = JSON.parse(readFileSync(outPath, "utf8"));
    assert.deepEqual(reread, sbom);
    assert.equal(reread.schema, SCHEMA);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("artifact binding requires a regular file and changes when its exact bytes change", () => {
  const dir = mkdtempSync(join(tmpdir(), "membrane-sbom-artifact-"));
  try {
    writeFileSync(join(dir, "pnpm-lock.yaml"), "packages:\n");
    writeFileSync(join(dir, "Cargo.lock"), "version = 4\n");
    const artifact = join(dir, "MembraneHub_1.0.0_x64-setup.exe");
    writeFileSync(artifact, "first installer bytes");
    const lockfiles = [{ ecosystem: "npm", path: "pnpm-lock.yaml" }, { ecosystem: "cargo", path: "Cargo.lock" }];
    const first = generateSbom({ repoRoot: dir, artifact: "MembraneHub_1.0.0_x64-setup.exe", lockfiles });
    writeFileSync(artifact, "changed installer bytes");
    const second = generateSbom({ repoRoot: dir, artifact: "MembraneHub_1.0.0_x64-setup.exe", lockfiles });
    assert.notEqual(first.artifact.sha256, second.artifact.sha256);
    assert.equal(second.artifact.size, Buffer.byteLength("changed installer bytes"));
    assert.throws(() => generateSbom({ repoRoot: dir, lockfiles }), /FAIL CLOSED: artifact is required/);
    assert.throws(() => generateSbom({ repoRoot: dir, artifact: "missing.exe", lockfiles }), /FAIL CLOSED: artifact not found/);
    assert.throws(() => generateSbom({ repoRoot: dir, artifact: ".", lockfiles }), /FAIL CLOSED: artifact must be a regular file/);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test("CLI requires --artifact and binds a fixture installer's exact bytes", () => {
  const dir = mkdtempSync(join(tmpdir(), "membrane-sbom-cli-"));
  try {
    const artifact = join(dir, "MembraneHub_1.0.0_x64-setup.exe");
    writeFileSync(artifact, "fixture installer bytes");
    const cli = resolve(REPO_ROOT, "scripts/release/evidence/sbom.mjs");
    const missing = spawnSync(process.execPath, [cli, "--repo-root", REPO_ROOT], { encoding: "utf8" });
    assert.notEqual(missing.status, 0);
    assert.match(missing.stderr, /FAIL CLOSED: artifact is required/);
    const result = spawnSync(process.execPath, [cli, "--repo-root", REPO_ROOT, "--artifact", artifact], { encoding: "utf8" });
    assert.equal(result.status, 0, result.stderr);
    const sbom = JSON.parse(result.stdout);
    assert.equal(sbom.artifact.path, artifact.replaceAll("\\", "/"));
    assert.equal(sbom.artifact.size, Buffer.byteLength("fixture installer bytes"));
    assert.equal(sbom.artifact.sha256, createHash("sha256").update("fixture installer bytes").digest("hex"));
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});
