//! Parity tests for `lib_generated_docs` (native port of
//! `blueprint/src/lib/generated-docs.mjs`), lane LIB4 (r5 closure).

use membrane_blueprint::lib_generated_docs::{
    generate_docs, generated_docs_generation_id, generation_header, is_generated,
    maintain_readme_pointer, DocsStats, GenerateDocsOptions, ReadmePointerMode, DOC_PATH_ARCHITECTURE,
    DOC_PATH_PRODUCT, VERSION,
};
use std::fs;

fn tempdir(name: &str) -> std::path::PathBuf {
    let mut dir = std::env::temp_dir();
    dir.push(format!("membrane-lib4-docs-{}-{}", name, std::process::id()));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).expect("create tempdir");
    dir
}

#[test]
fn version_is_pinned() {
    assert_eq!(VERSION, "0.2.0");
}

#[test]
fn generation_id_excludes_generated_paths_and_is_deterministic() {
    let files1 = vec![
        "src/a.rs".to_string(),
        "README.md".to_string(), // excluded
        DOC_PATH_PRODUCT.to_string(), // excluded
    ];
    let files2 = vec!["src/a.rs".to_string()];
    let stats = DocsStats { files: 3, docs: 1, claims: 2, code_refs: 4 };
    let id1 = generated_docs_generation_id(&files1, &stats, "sig-1");
    let id2 = generated_docs_generation_id(&files2, &stats, "sig-1");
    assert_eq!(id1, id2, "excluded paths must not perturb the id");
    assert_eq!(id1.len(), 32, "xxh3-128 hex digest is 32 chars");

    let id3 = generated_docs_generation_id(&files2, &stats, "sig-2");
    assert_ne!(id1, id3, "different source signature must change id");
}

#[test]
fn generation_header_matches_legacy_format() {
    let header = generation_header("abc123");
    assert!(header.starts_with("<!-- generated by blueprint 0.2.0 gen:abc123"));
    assert!(header.ends_with("-->"));
}

#[test]
fn is_generated_true_for_missing_file() {
    let dir = tempdir("isgen-missing");
    let path = dir.join("nope.md");
    assert!(is_generated(&path));
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn is_generated_checks_first_line_prefix() {
    let dir = tempdir("isgen");
    let generated = dir.join("generated.md");
    fs::write(&generated, "<!-- generated by blueprint 0.2.0 gen:x -->\ncontent").unwrap();
    assert!(is_generated(&generated));

    let handwritten = dir.join("handwritten.md");
    fs::write(&handwritten, "# My hand-written doc\n").unwrap();
    assert!(!is_generated(&handwritten));

    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn maintain_readme_pointer_absent_when_no_readme() {
    let dir = tempdir("readme-absent");
    let mode = maintain_readme_pointer(&dir).unwrap();
    assert_eq!(mode, ReadmePointerMode::Absent);
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn maintain_readme_pointer_creates_block_first_time() {
    let dir = tempdir("readme-create");
    fs::write(dir.join("README.md"), "# My Project\n\nSome content.\n").unwrap();
    let mode = maintain_readme_pointer(&dir).unwrap();
    assert_eq!(mode, ReadmePointerMode::Created);
    let text = fs::read_to_string(dir.join("README.md")).unwrap();
    assert!(text.contains("<!-- blueprint:docs:start -->"));
    assert!(text.contains("<!-- blueprint:docs:end -->"));
    assert!(text.contains("[Product overview](docs/product.md)"));
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn maintain_readme_pointer_is_idempotent_on_second_call() {
    let dir = tempdir("readme-idempotent");
    fs::write(dir.join("README.md"), "# My Project\n").unwrap();
    maintain_readme_pointer(&dir).unwrap();
    let first = fs::read_to_string(dir.join("README.md")).unwrap();
    let mode = maintain_readme_pointer(&dir).unwrap();
    assert_eq!(mode, ReadmePointerMode::Updated);
    let second = fs::read_to_string(dir.join("README.md")).unwrap();
    assert_eq!(first, second, "second run must not perturb an already-correct block");
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn maintain_readme_pointer_updates_stale_block_content() {
    let dir = tempdir("readme-update");
    let stale = "# Proj\n<!-- blueprint:docs:start -->\nOLD CONTENT\n<!-- blueprint:docs:end -->\nTail text\n";
    fs::write(dir.join("README.md"), stale).unwrap();
    let mode = maintain_readme_pointer(&dir).unwrap();
    assert_eq!(mode, ReadmePointerMode::Updated);
    let text = fs::read_to_string(dir.join("README.md")).unwrap();
    assert!(!text.contains("OLD CONTENT"));
    assert!(text.contains("Tail text"));
    assert!(text.contains("[Architecture](docs/architecture.md)"));
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn generate_docs_missing_map_short_circuits() {
    let dir = tempdir("gen-missing-map");
    let result = generate_docs(&dir, GenerateDocsOptions::default()).unwrap();
    assert_eq!(result.mode, "missing_map");
    assert!(result.wrote.is_empty());
    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn generate_docs_writes_fresh_docs_and_readme_pointer() {
    let dir = tempdir("gen-write");
    let agent = dir.join(".agent");
    fs::create_dir_all(&agent).unwrap();
    fs::write(
        agent.join("map.json"),
        r#"{"repo":"demo-repo","stats":{"files":1,"docs":0,"claims":0,"codeRefs":0},"nodes":[]}"#,
    )
    .unwrap();
    fs::write(dir.join("README.md"), "# demo-repo\n").unwrap();

    let result = generate_docs(&dir, GenerateDocsOptions::default()).unwrap();
    assert_eq!(result.mode, "wrote");
    assert_eq!(result.wrote, vec![DOC_PATH_PRODUCT.to_string(), DOC_PATH_ARCHITECTURE.to_string()]);
    assert!(dir.join(DOC_PATH_PRODUCT).exists());
    assert!(dir.join(DOC_PATH_ARCHITECTURE).exists());
    assert_eq!(result.readme, Some(ReadmePointerMode::Created));

    let product_text = fs::read_to_string(dir.join(DOC_PATH_PRODUCT)).unwrap();
    assert!(product_text.starts_with("<!-- generated by blueprint"));
    assert!(product_text.contains("demo-repo — Product Overview"));

    // Re-running with unchanged inputs regenerates the SAME generation id
    // (byte-identical rebuild on an unchanged repo).
    let result2 = generate_docs(&dir, GenerateDocsOptions::default()).unwrap();
    assert_eq!(result2.mode, "wrote");
    let product_text2 = fs::read_to_string(dir.join(DOC_PATH_PRODUCT)).unwrap();
    assert_eq!(product_text, product_text2);

    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn generate_docs_reports_conflict_for_handwritten_target() {
    let dir = tempdir("gen-conflict");
    let agent = dir.join(".agent");
    fs::create_dir_all(&agent).unwrap();
    fs::write(
        agent.join("map.json"),
        r#"{"repo":"demo","stats":{},"nodes":[]}"#,
    )
    .unwrap();
    let docs_dir = dir.join("docs");
    fs::create_dir_all(&docs_dir).unwrap();
    fs::write(docs_dir.join("product.md"), "# Hand-written product doc\n").unwrap();
    fs::write(docs_dir.join("architecture.md"), "# Hand-written arch doc\n").unwrap();

    let result = generate_docs(&dir, GenerateDocsOptions::default()).unwrap();
    assert_eq!(result.mode, "docs_conflict");
    assert_eq!(result.conflicts.len(), 2);
    assert_eq!(result.fallback.len(), 2);
    assert!(dir.join(".agent/docs/product.md").exists());
    assert!(dir.join(".agent/docs/architecture.md").exists());
    // Hand-written targets must be left untouched.
    assert_eq!(
        fs::read_to_string(docs_dir.join("product.md")).unwrap(),
        "# Hand-written product doc\n"
    );

    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn generate_docs_no_readme_link_skips_readme_maintenance() {
    let dir = tempdir("gen-no-readme");
    let agent = dir.join(".agent");
    fs::create_dir_all(&agent).unwrap();
    fs::write(agent.join("map.json"), r#"{"repo":"demo","stats":{},"nodes":[]}"#).unwrap();
    fs::write(dir.join("README.md"), "# demo\n").unwrap();

    let result = generate_docs(&dir, GenerateDocsOptions { no_readme_link: true }).unwrap();
    assert_eq!(result.mode, "wrote");
    assert_eq!(result.readme, None);
    let readme_text = fs::read_to_string(dir.join("README.md")).unwrap();
    assert!(!readme_text.contains("blueprint:docs:start"));

    let _ = fs::remove_dir_all(&dir);
}

#[test]
fn generate_docs_retires_start_here_on_success() {
    let dir = tempdir("gen-retire-start-here");
    let agent = dir.join(".agent");
    fs::create_dir_all(&agent).unwrap();
    fs::write(agent.join("map.json"), r#"{"repo":"demo","stats":{},"nodes":[]}"#).unwrap();
    fs::write(agent.join("START-HERE.md"), "old bootstrap doc").unwrap();

    let result = generate_docs(&dir, GenerateDocsOptions { no_readme_link: true }).unwrap();
    assert_eq!(result.retired, vec![".agent/START-HERE.md".to_string()]);
    assert!(!agent.join("START-HERE.md").exists());

    let _ = fs::remove_dir_all(&dir);
}
