// lib/generated-docs.mjs — Cortex B6.5 generated human docs
//
// Regenerates docs/product.md and docs/architecture.md with:
//   - generation header (no timestamp; byte-identical on unchanged repo)
//   - per-section provenance (path:line, claim id, or graph query reference)
//   - clobber safety (typed docs_conflict when a hand-written file lacks the
//     generation marker; falls back to .agent/docs/)
//   - optional README pointer block (idempotent, --no-readme-link opt-out)
//   - START-HERE.md retirement on every successful build

import { createXXHash128 } from "hash-wasm";

// XXH3-128 for the doc source-set identity. This is a content/identity hash for
// regenerable docs, not a security boundary, so a fast non-cryptographic hash is
// the correct tool. It was sha1 — weaker AND slower than what replaced it.
const xxhasher = await createXXHash128();
import {
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { openStoreReadOnly, closeStore } from "../graph/store-sqlite.mjs";

// The graph manifest lives in the store, not on disk as JSON. Returns null when
// no graph has been built, which the caller already handles by falling back to
// a file-list hash.
function readStoredManifest(root) {
  const dbPath = join(root, ".agent/graph/graph.db");
  if (!existsSync(dbPath)) return null;
  try {
    const db = openStoreReadOnly(dbPath);
    try {
      const row = db.prepare("SELECT value FROM generation WHERE key = 'manifest'").get();
      return row ? JSON.parse(row.value) : null;
    } finally {
      closeStore(db);
    }
  } catch {
    return null;
  }
}

export const VERSION = "0.2.0";
const GENERATION_HEADER_PREFIX = "<!-- generated by cortex";
const MARKER = "<!-- cortex:docs:start -->";
const END_MARKER = "<!-- cortex:docs:end -->";
export const DOC_PATHS = Object.freeze({
  product: "docs/product.md",
  architecture: "docs/architecture.md",
});
const FALLBACK_DIR = ".agent/docs";
const START_HERE_PATH = ".agent/START-HERE.md";
// Files excluded from the generation-id input set because they ARE generated
// (or partially generated) by this very emitter. Keeping them out of the hash
// is what makes an unchanged rebuild byte-identical.
const ID_EXCLUDE = new Set(["README.md", DOC_PATHS.product, DOC_PATHS.architecture]);

function readJson(path) {
  if (!existsSync(path)) return null;
  return JSON.parse(readFileSync(path, "utf8"));
}

function readOptionalJson(path) {
  try {
    return readJson(path);
  } catch {
    return null;
  }
}

function xxh3Hex(input) {
  xxhasher.init();
  xxhasher.update(input);
  return xxhasher.digest("hex");
}

// Stable identifier for the source set: portable source signature + paths + repo stats, deliberately
// excluding generated/pointer-block paths. Recompute on every generateDocs
// call so an unchanged rebuild yields the same id and byte-identical output.
export function generatedDocsGenerationId({ repo, files, stats, sourceSignature }) {
  const sortedPaths = (files ?? [])
    .map((entry) => entry.path ?? entry)
    .filter((path) => path && !ID_EXCLUDE.has(path))
    .sort()
    .join("\n");
  return xxh3Hex(
    [
      String(repo ?? "").toLowerCase(),
      sourceSignature ?? "",
      sortedPaths,
      String(stats?.files ?? 0),
      String(stats?.docs ?? 0),
      String(stats?.claims ?? 0),
      String(stats?.codeRefs ?? 0),
    ].join("\n"),
  );
}

export function generationHeader(generationId) {
  return `${GENERATION_HEADER_PREFIX} ${VERSION} gen:${generationId} — edit code/docs sources, not this file -->`;
}

export function isGenerated(targetPath) {
  if (!existsSync(targetPath)) return true;
  const text = readFileSync(targetPath, "utf8");
  // The pointer block uses raw HTML comments; the generation header is a
  // single HTML comment with the marker prefix. Match the start of the file
  // (after any BOM) to the marker.
  const firstLine = text.split(/\r?\n/, 1)[0] ?? "";
  return firstLine.startsWith(GENERATION_HEADER_PREFIX);
}

function writeText(path, body) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, body.endsWith("\n") ? body : `${body}\n`);
}

// ── Product doc ─────────────────────────────────────────────────────────

function productSections({ repo, claims, map, generationId }) {
  const header = generationHeader(generationId);
  const eligible = (claims ?? []).filter(
    (c) => ["implemented", "partial", "claim"].includes(c.status) && c.text && c.text.length > 0,
  );
  const bySource = new Map();
  for (const c of eligible) {
    if (!bySource.has(c.source)) bySource.set(c.source, []);
    bySource.get(c.source).push(c);
  }
  const sortedSources = [...bySource.entries()].sort((a, b) => a[0].localeCompare(b[0]));
  const capabilityRows = sortedSources.slice(0, 12).map(([path, list]) => {
    const top = list[0];
    return `- **${path}** — ${top.text} _(source: ${top.source}:${top.line})_`;
  });
  const canonical = ["AGENTS.md", "CLAUDE.md", "README.md"];
  const surfaceRows = (map?.nodes ?? [])
    .filter((n) => n.kind === "doc" && canonical.includes(n.path))
    .map((n) => `- \`${n.path}\` _(source: ${n.path}:1)_`)
    .slice(0, 5);
  return [
    header,
    "",
    `# ${repo} — Product Overview`,
    "",
    "Code-grounded description of what this product is and does. Generated from verified doc claims;",
    "audience and positioning statements come **only** from existing repository docs, never invented.",
    "",
    "## Capabilities",
    "",
    "Plain-language features derived from the verified claim inventory. Each row points back to its source.",
    "",
    ...(capabilityRows.length ? capabilityRows : ["- _No verified capability claims yet._"]),
    "",
    "## Entry points",
    "",
    "User-visible surfaces named by the repository docs:",
    "",
    ...(surfaceRows.length ? surfaceRows : ["- _No canonical entry-point docs found._"]),
    "",
    "## Honesty / Gaps",
    "",
    "Items the docs claim but no implementation file references — and the reverse — surface here as",
    "findings. If a flow is named in user-facing copy but absent from the code graph, it is listed",
    "below, not omitted.",
    "",
    "- _See `.agent/stale.json` for the canonical missing-reference list (provenance: .agent/stale.json)._",
    "",
  ].join("\n");
}

// ── Architecture doc ────────────────────────────────────────────────────

function markdownCell(value) {
  return String(value ?? "")
    .replaceAll("|", "\\|")
    .replace(/\s+/g, " ")
    .trim();
}

function workflowStepText(step) {
  if (typeof step === "string") return step;
  if (!step || typeof step !== "object") return "";
  return step.name ?? step.component ?? step.label ?? step.step ?? step.id ?? "";
}

function workflowSteps(flow) {
  if (typeof flow === "string") {
    return flow.split(/\s*(?:->|→)\s*/).map((step) => step.trim()).filter(Boolean);
  }
  if (Array.isArray(flow)) return flow.map(workflowStepText).map((step) => step.trim()).filter(Boolean);
  if (!flow || typeof flow !== "object") return [];
  const structured = flow.steps ?? flow.path ?? flow.components;
  if (Array.isArray(structured)) {
    return structured.map(workflowStepText).map((step) => step.trim()).filter(Boolean);
  }
  const text = flow.flow ?? flow.dataFlow ?? flow.description;
  return typeof text === "string" ? workflowSteps(text) : [];
}

function compactWorkflowLabel(value) {
  let label = String(value ?? "").replaceAll("`", "").replace(/\s+/g, " ").trim();
  const colon = label.indexOf(":");
  if (colon > 0 && colon <= 48 && !label.slice(0, colon).includes("::")) label = label.slice(0, colon);
  label = label.replace(/[.;,]\s*$/, "");
  if (label.length > 88) label = `${label.slice(0, 85).trimEnd()}…`;
  return label
    .replaceAll("\\", "/")
    .replaceAll('"', "'")
    .replaceAll("\n", " ");
}

function componentWorkflowMermaid(architecture) {
  const chains = (architecture?.dataFlow ?? [])
    .map(workflowSteps)
    .map((steps) => steps.map(compactWorkflowLabel).filter(Boolean))
    .filter((steps) => steps.length >= 2);
  if (!chains.length) return null;

  const ids = new Map();
  const edges = new Set();
  for (const chain of chains) {
    for (const label of chain) {
      if (!ids.has(label)) ids.set(label, `c${ids.size}`);
    }
    for (let index = 0; index < chain.length - 1; index += 1) {
      edges.add(`${ids.get(chain[index])} --> ${ids.get(chain[index + 1])}`);
    }
  }

  return [
    "flowchart LR",
    "  %% component workflow from .agent/understanding.json",
    ...[...ids.entries()].map(([label, id]) => `  ${id}["${label}"]`),
    ...[...edges].map((edge) => `  ${edge}`),
  ].join("\n");
}

function architectureSections({ repo, map, stale, understanding, generationId }) {
  const header = generationHeader(generationId);
  const architecture = understanding?.architecture ?? {};
  const componentRows = (architecture.components ?? []).map((component) => {
    const name = markdownCell(component?.name ?? component?.component ?? "Unnamed component");
    const note = markdownCell(component?.note ?? component?.role ?? "");
    const evidence = markdownCell(component?.evidence ?? "Undetermined — no evidence recorded");
    return `- **${name}**${note ? ` — ${note}` : ""} _(source: ${evidence})_`;
  });
  const workflow = componentWorkflowMermaid(architecture);
  const missingCount = (stale?.missingReferences ?? []).length;
  const staleClaimsCount = (stale?.staleClaims ?? []).length;
  const classifiedFlows = architecture.flows ?? [];
  const flowRows = classifiedFlows.length
    ? [
        "| Flow | Status | Evidence | Impact |",
        "|---|---|---|---|",
        ...classifiedFlows.map((flow) =>
          `| ${markdownCell(flow?.name ?? flow?.flow ?? "Unnamed flow")} | ${markdownCell(flow?.status ?? "undetermined")} | ${markdownCell(flow?.evidence ?? "Undetermined")} | ${markdownCell(flow?.impact ?? "")} |`,
        ),
      ]
    : ["_No classified product flows yet; run Cortex Phase 2 synthesis._"];
  const synthesizedCoverage = architecture.capabilityCoverage ?? [];
  const capabilityRows = synthesizedCoverage.length
    ? [
        "| Capability | Status | Evidence | Provider |",
        "|---|---|---|---|",
        ...synthesizedCoverage.map((row) =>
          `| ${markdownCell(row?.capability ?? row?.name ?? "Unnamed capability")} | ${markdownCell(row?.status ?? "undetermined")} | ${markdownCell(row?.evidence ?? "Undetermined")} | ${markdownCell(row?.provider ?? "")} |`,
        ),
      ]
    : [
        "| Capability | Status | Evidence |",
        "|---|---|---|",
        "| document/ADR/plan claims | covered | _source: .agent/map.json:claims_ |",
        "| code symbols and relationships | partial until Phase 2 classifies provider coverage | _source: .agent/graph/graph.db_ |",
        "| contradiction/staleness arbitration | covered | _source: .agent/stale.json_ |",
      ];
  return [
    header,
    "",
    `# ${repo} — Architecture`,
    "",
    "Technical overview of components, interfaces, classified flow inventory, and capability coverage.",
    "The deterministic Phase-1 graph supplies the evidence substrate; Phase-2 understanding supplies",
    "the human component names and operational flow. Raw file and symbol nodes are intentionally omitted.",
    "",
    ...(architecture.summary ? [markdownCell(architecture.summary), ""] : []),
    "## System workflow",
    "",
    ...(workflow
      ? ["```mermaid", workflow, "```", "", "_(source: .agent/understanding.json:architecture.dataFlow)_"]
      : ["_No synthesized component workflow yet; run Cortex Phase 2 synthesis._"]),
    "",
    "## Components",
    "",
    ...(componentRows.length ? componentRows : ["- _No synthesized components yet; run Cortex Phase 2 synthesis._"]),
    "",
    "## Flow inventory",
    "",
    ...flowRows,
    "",
    "## Capability coverage",
    "",
    ...capabilityRows,
    "",
    "## Health & Security (loud-partial when graph is missing)",
    "",
    `- Stale claims: **${staleClaimsCount}** _(source: .agent/stale.json:staleClaims)_`,
    `- Missing references: **${missingCount}** _(source: .agent/stale.json:missingReferences)_`,
    "- Detailed health and security findings live in `.agent/understanding.json`; every synthesized",
    "  component and flow above retains its recorded evidence. _(source: .agent/understanding.json)_",
    "",
    "## Status",
    "",
    `Generated from index signature \`${generationId}\`. Unchanged-repo rebuilds are byte-identical.`,
    "",
  ].join("\n");
}

// ── README pointer ─────────────────────────────────────────────────────

export function maintainReadmePointer(root) {
  const readmePath = join(root, "README.md");
  if (!existsSync(readmePath)) return { mode: "readme_absent" };
  const text = readFileSync(readmePath, "utf8");
  const block = [
    MARKER,
    "## Repository truth docs",
    "- [Product overview](docs/product.md) — what this is and does (generated, code-grounded)",
    "- [Architecture](docs/architecture.md) — components, flows, interfaces (generated, code-grounded)",
    END_MARKER,
  ].join("\n");
  const startIdx = text.indexOf(MARKER);
  const endIdx = startIdx === -1 ? -1 : text.indexOf(END_MARKER, startIdx);
  if (startIdx === -1 || endIdx === -1) {
    // First-time creation: append with a single trailing newline so the file
    // ends canonically. The signature computation strips the block (and the
    // separator newline) before hashing, so adding the block does not perturb
    // the next source signature.
    const next = text.endsWith("\n") ? `${text}\n${block}\n` : `${text}\n${block}\n`;
    writeText(readmePath, next);
    return { mode: "created" };
  }
  const before = text.slice(0, startIdx);
  const afterRaw = text.slice(endIdx + END_MARKER.length);
  const after = afterRaw.trim()
    ? (/^\r?\n/.test(afterRaw) ? afterRaw : `\n${afterRaw}`)
    : "\n";
  const next = `${before}${block}${after}`;
  if (next !== text) writeText(readmePath, next);
  return { mode: "updated" };
}

// ── Orchestrator ───────────────────────────────────────────────────────

export function generateDocs(root, opts = {}) {
  const noReadmeLink = Boolean(opts.noReadmeLink);
  const map = readJson(join(root, ".agent/map.json"));
  if (!map) {
    return { mode: "missing_map", conflicts: [], wrote: [], fallback: [], readme: null };
  }
  const claims = readJson(join(root, ".agent/claims.json")) ?? [];
  const stale = readJson(join(root, ".agent/stale.json")) ?? {
    missingReferences: [],
    staleClaims: [],
  };
  const understandingCandidate = readOptionalJson(join(root, ".agent/understanding.json")) ?? null;
  const index = readJson(join(root, ".agent/index.json")) ?? {
    files: [],
    sourceSignature: "no-index",
  };
  // Graph identity validates optional Phase-2 understanding. Tracked docs use
  // portable Phase-1 source identity so clean clones reproduce exact bytes.
  const graphManifest = readStoredManifest(root);
  const graphGenerationId = graphManifest?.generationId ?? null;
  const understanding = graphGenerationId
    && understandingCandidate?.sourceGenerationId === graphGenerationId
    ? understandingCandidate
    : null;
  const generationId = generatedDocsGenerationId({
    repo: map.repo,
    files: index.files ?? [],
    stats: map.stats,
    sourceSignature: index.sourceSignature,
  });
  const inputs = { repo: map.repo, map, claims, stale, understanding, generationId };
  const productBody = productSections(inputs);
  const archBody = architectureSections(inputs);
  const targetProduct = join(root, DOC_PATHS.product);
  const targetArch = join(root, DOC_PATHS.architecture);
  const conflicts = [];
  if (!isGenerated(targetProduct)) conflicts.push(DOC_PATHS.product);
  if (!isGenerated(targetArch)) conflicts.push(DOC_PATHS.architecture);
  const result = {
    mode: conflicts.length ? "docs_conflict" : "wrote",
    conflicts,
    wrote: [],
    fallback: [],
    readme: null,
    retired: [],
  };
  if (conflicts.length) {
    const fallbackDir = join(root, FALLBACK_DIR);
    writeText(join(fallbackDir, "product.md"), productBody);
    writeText(join(fallbackDir, "architecture.md"), archBody);
    result.fallback = [DOC_PATHS.product, DOC_PATHS.architecture];
    return result;
  }
  writeText(targetProduct, productBody);
  writeText(targetArch, archBody);
  result.wrote = [DOC_PATHS.product, DOC_PATHS.architecture];
  if (!noReadmeLink) {
    result.readme = maintainReadmePointer(root);
  }
  const startHere = join(root, START_HERE_PATH);
  if (existsSync(startHere)) {
    rmSync(startHere);
    result.retired.push(START_HERE_PATH);
  }
  return result;
}

export const _internal = { productSections, architectureSections, componentWorkflowMermaid };
