import test from "node:test"; import assert from "node:assert/strict";
test("hub shell exposes offline truthful initial state", async()=>{const html=await (await import("node:fs/promises")).readFile(new URL("../index.html",import.meta.url),"utf8"); assert.match(html,/Offline — no snapshot cached/); assert.match(html,/Waiting for Hub-owned Membrane service/);});
test("tray surface keeps keyboard focus and startup opt-in explicit", async()=>{const html=await (await import("node:fs/promises")).readFile(new URL("../index.html",import.meta.url),"utf8"); assert.match(html,/aria-live="polite"/); assert.match(html,/tabindex="0"/); assert.match(html,/Launch Membrane Hub at login/); assert.match(html,/invoke\('set_startup',\{enabled:startup\.checked\}\)/); assert.match(html,/import\('\.\/vendor\/@tauri-apps\/api\/core\.js'\)/); assert.doesNotMatch(html,/type="importmap"|Available in native Hub|managed outside/);});
test("hidden tray window resumes focus and reads actual startup state", async()=>{const html=await (await import("node:fs/promises")).readFile(new URL("../index.html",import.meta.url),"utf8"); assert.match(html,/onFocusChanged/); assert.match(html,/current\.hide\(\)/); assert.match(html,/invoke\('startup_setting'\)/); assert.match(html,/hub-snapshot-tick/);});
test("native Hub separates hidden menu-bar snapshot from explicit Dock dashboard", async()=>{const fs=await import("node:fs/promises"); const config=JSON.parse(await fs.readFile(new URL("../src-tauri/tauri.conf.json",import.meta.url),"utf8")); assert.deepEqual(config.app.windows.map(({label,url})=>({label,url})),[{label:"hub",url:"popover.html"},{label:"dashboard",url:"index.html"}]); const [popover,dashboard]=config.app.windows; assert.equal(popover.visible,false); assert.equal(popover.decorations,false); assert.equal(popover.skipTaskbar,true); assert.equal(dashboard.visible,false); assert.equal(dashboard.decorations,true); assert.equal(dashboard.skipTaskbar,false); const plist=await fs.readFile(new URL("../src-tauri/Info.plist",import.meta.url),"utf8"); assert.match(plist,/<key>LSUIElement<\/key>\s*<true\/>/); const rust=await fs.readFile(new URL("../src-tauri/src/main.rs",import.meta.url),"utf8"); assert.match(rust,/fn open_dashboard/); assert.match(rust,/single_instance::init\(\|app[\s\S]*show_dashboard\(app\)/); assert.match(rust,/ActivationPolicy::Regular/); assert.match(rust,/CloseRequested[\s\S]*ActivationPolicy::Accessory/); const started=rust.indexOf("supervisor.start()"); assert.doesNotMatch(rust.slice(started,started+700),/window\.show\(\)/);});
test("both local UI windows have a bounded Tauri IPC capability", async()=>{const fs=await import("node:fs/promises"); const capability=JSON.parse(await fs.readFile(new URL("../src-tauri/capabilities/default.json",import.meta.url),"utf8")); assert.equal(capability.identifier,"hub-local-ui"); assert.deepEqual(capability.windows,["hub","dashboard"]); assert.deepEqual(capability.permissions,["core:default"]);});
test("frontend build dereferences pnpm-linked Tauri API into bundle", async()=>{const fs=await import("node:fs/promises"); const script=await fs.readFile(new URL("../scripts/build-frontend.mjs",import.meta.url),"utf8"); assert.match(script,/node_modules\/@tauri-apps\/api[\s\S]*dereference: true/);});
test("Hub records bounded structured telemetry & exposes diagnostics", async()=>{const fs=await import("node:fs/promises"); const rust=await fs.readFile(new URL("../src-tauri/src/hub_telemetry.rs",import.meta.url),"utf8"); const supervisor=await fs.readFile(new URL("../src-tauri/src/supervisor.rs",import.meta.url),"utf8"); const main=await fs.readFile(new URL("../src-tauri/src/main.rs",import.meta.url),"utf8"); const popover=await fs.readFile(new URL("../src/popover.mjs",import.meta.url),"utf8"); assert.match(rust,/MAX_LOG_BYTES/); assert.match(rust,/schemaVersion/); assert.match(rust,/previous\.jsonl/); assert.match(rust,/resident_log_path/); assert.match(supervisor,/MAX_RESIDENT_LOG_BYTES/); assert.match(supervisor,/Stdio::from\(resident_log\)/); assert.match(main,/fn diagnostics_report/); assert.match(popover,/invoke\('diagnostics_report'\)/);});
test("dev runner supplies explicit workspace authority before Tauri starts", async()=>{const fs=await import("node:fs/promises"); const dev=await fs.readFile(new URL("../scripts/dev.mjs",import.meta.url),"utf8"); assert.match(dev,/MEMBRANE_WORKSPACE_ROOT: workspaceRoot/); assert.match(dev,/\["exec", "tauri", "dev", "--no-watch"\]/);});
