import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { assertNsisInPlaceUpgradeContract } from "@rightkit/release/nsis-upgrade-contract.mjs";

const hub = resolve(fileURLToPath(new URL("..", import.meta.url)));
const pkg = JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8"));
const config = (await import(new URL(`../right-release.config.mjs?windows-test=${Date.now()}`, import.meta.url))).default;
const windowsBuild = readFileSync(new URL("../scripts/build-windows-release.mjs", import.meta.url), "utf8");
const frontendBuild = readFileSync(new URL("../scripts/build-frontend.mjs", import.meta.url), "utf8");
const releaseIdentity = readFileSync(new URL("../scripts/release-identity.mjs", import.meta.url), "utf8");
const tauriConfig = JSON.parse(readFileSync(new URL("../src-tauri/tauri.conf.json", import.meta.url), "utf8"));
const windowsTauriConfig = JSON.parse(readFileSync(new URL("../src-tauri/tauri.windows.conf.json", import.meta.url), "utf8"));
const nsisTemplate = readFileSync(new URL("../src-tauri/windows/installer.nsi", import.meta.url), "utf8");
const qualification = readFileSync(new URL("../../../scripts/qualification/install-release.ps1", import.meta.url), "utf8");

test("Windows release is signed, sealed & stays local", () => {
  assert.equal(pkg.devDependencies["@tauri-apps/cli"], "2.11.4");
  assert.equal(pkg.scripts["rightkit:package:win"], "node scripts/build-windows-release.mjs");
  assert.equal(pkg.scripts["release:identity"], "node scripts/release-identity.mjs --out dist/release-identity.json");
  assert.equal(pkg.scripts["release:evidence:win"], "node scripts/write-windows-release-evidence.mjs");
  assert.match(pkg.scripts["release:prepare:sidecars:win"], /pnpm run build/);
  assert.match(pkg.scripts["release:prepare:sidecars:win"], /right-release sign-windows .*cortex-.*\.exe .*membrane-.*\.exe/);
  assert.match(pkg.scripts["release:prepare:sidecars:win"], /right-release sign-windows --verify-only/);
  assert.equal(pkg.scripts["release:build:win"], "pnpm exec right-release build --platform win");
  const target = config.targets.win;
  assert.equal(target.signed, true);
  assert.equal(target.signingContract, "windows-raw-exe-authenticode-before-nsis-v1");
  assert.equal(target.prePackage.cmd, "pnpm");
  assert.deepEqual(target.prePackage.args, ["run", "rightkit:package:win", "--", "raw"]);
  assert.deepEqual(target.package.args, ["run", "rightkit:package:win", "--", "package"]);
  assert.deepEqual(target.sign.prePackageFiles, ["src-tauri/target/x86_64-pc-windows-msvc/release/membrane-hub.exe"]);
  assert.equal(target.sign.prePackageFiles.length, 1);
  assert.notEqual(target.sign.prePackageFiles[0], target.sign.files[0]);
  assert.deepEqual(target.artifacts, target.sign.files);
  assert.equal(target.installer.artifacts[0].file, target.sign.files[0]);
  assert.equal(target.updater.artifacts[0].file, target.sign.files[0]);
  assert.equal(target.updater.artifacts[0].signature, `${target.sign.files[0]}.sig`);
  assert.match(target.installer.artifacts[0].key, /installers\/windows\/current\/Membrane_x64-setup\.exe$/);
  assert.match(target.updater.artifacts[0].key, /updates\/windows\/current\/Membrane_x64-setup\.exe$/);
  assert.doesNotMatch(JSON.stringify(target), /upload|publish/);
  assert.equal(tauriConfig.bundle.publisher, "Adrian D'souza");
  assert.equal(windowsTauriConfig.bundle.windows.allowDowngrades, true);
  assert.equal(windowsTauriConfig.bundle.windows.nsis.allowDowngrades, undefined);
  assert.equal(tauriConfig.app.security.freezePrototype, true);
  assert.deepEqual(tauriConfig.app.security.capabilities, ["hub-local-ui"]);
  assert.match(tauriConfig.app.security.csp, /default-src 'self'/);
  assert.match(tauriConfig.app.security.csp, /object-src 'none'/);
  assert.doesNotMatch(tauriConfig.app.security.csp, /unsafe-(?:inline|eval)/);
  assert.match(nsisTemplate, /!define INSTALLIDENTITY "Membrane Hub"/);
  assert.doesNotMatch(nsisTemplate, /Unsloth Studio/);
});

test("Windows package creates raw EXE before signing, then bundles without rebuilding it", () => {
  assert.match(windowsBuild, /process\.platform !== "win32"/);
  assert.match(windowsBuild, /const phase = process\.argv\[2\]/);
  assert.match(windowsBuild, /<raw\|package>/);
  assert.match(windowsBuild, /scripts\/stage-runtime\.mjs/);
  assert.match(windowsBuild, /const triple = "x86_64-pc-windows-msvc"/);
  assert.match(windowsBuild, /--target", triple/);
  assert.match(windowsBuild, /--no-bundle/);
  assert.match(windowsBuild, /"tauri", "bundle"/);
  assert.match(windowsBuild, /"--bundles", "nsis"/);
  assert.match(windowsBuild, /MEMBRANE_SIDECARS_READY/);
  assert.match(windowsBuild, /MEMBRANE_SIGNED_SIDECARS_READY/);
  assert.match(windowsBuild, /signed Windows sidecars are not prepared/);
  assert.match(windowsBuild, /resolveTargetRoot/);
  assert.match(windowsBuild, /managed raw Hub executable/);
  assert.match(windowsBuild, /signed raw Hub executable/);
  assert.match(windowsBuild, /managed NSIS installer/);
  assert.doesNotMatch(windowsBuild, /sign-windows|signtool|Azure/);
  const rawBuild = windowsBuild.slice(windowsBuild.indexOf('phase === "raw"'), windowsBuild.indexOf("} else {"));
  const packageBuild = windowsBuild.slice(windowsBuild.indexOf("} else {"));
  assert.match(rawBuild, /"tauri", "build"/);
  assert.doesNotMatch(rawBuild, /--bundles/);
  assert.match(rawBuild, /run\("pnpm", \["run", "build"\], \{ sidecarsReady: true \}\)/);
  assert.match(rawBuild, /run\("node", \["scripts\/stage-runtime\.mjs"\], \{ sidecarsReady: true \}\)/);
  assert.ok(rawBuild.indexOf('run("pnpm", ["run", "build"])') < rawBuild.indexOf('scripts/stage-runtime.mjs'));
  assert.match(packageBuild, /"tauri", "bundle"/);
  assert.doesNotMatch(packageBuild, /"tauri", "build"/);
  assert.match(frontendBuild, /spawnSync\(rightkit, \["cargo", "build"/);
  assert.match(frontendBuild, /--message-format=json-render-diagnostics/);
  assert.match(frontendBuild, /message\.reason !== "compiler-artifact"/);
  assert.doesNotMatch(frontendBuild, /--target-dir|CARGO_TARGET_DIR|resolveManagedCargoTarget/);
  assert.doesNotMatch(frontendBuild, /spawnSync\((?:process\.env\.CARGO|"cargo")/);
  assert.match(frontendBuild, /writeEngineReleaseIdentity/);
  assert.match(releaseIdentity, /writeEngineReleaseIdentity/);
  assert.match(frontendBuild, /x86_64-pc-windows-msvc/);
  assert.doesNotMatch(frontendBuild, /spawnSync\("rightkit"/);
  assert.doesNotThrow(() => assertNsisInPlaceUpgradeContract(hub, config.targets.win.nsisUpgradeContract));
});

test("installed Windows qualification binds package evidence & exercises native cutover lifecycle", () => {
  for (const term of ["Get-AuthenticodeSignature", "ReleaseManifest", "Sbom", "Get-FileHash", "PreviousInstaller", "uninstall.exe", "/health", "tools/list", "msedgewebview2", "membrane native host", "cortex native host", "native-only steady-state", "WINDIR\\System32"]) assert.ok(qualification.toLowerCase().includes(term.toLowerCase()), term);
  assert.match(qualification, /Invoke-Installer \$installerPath[\s\S]*Invoke-Installer \$previousPath[\s\S]*Invoke-Installer \$installerPath/);
  assert.doesNotMatch(qualification, /Invoke-WebRequest|curl|upload/i);
  assert.match(JSON.stringify(config.buildInputs), /\.\.\/\.\.\/blueprint\/release\/\*\*/);
});
