//! Supervisor-issued lease. The supervisor mints a fresh lease every time it (re)spawns the
//! resident, hands it to the resident via `--lease <path>`, and republishes its sibling
//! discovery record so client adapters can find the supervisor's loopback endpoint.
//!
//! The lease shape is intentionally separate from the manifest (see
//! `membrane_protocol::installation::InstallationManifestV1`): the manifest is a
//! peer-to-peer identity that pins installation, schema, and data-root; the lease is a
//! supervisor-to-resident authority that pins instance identity and lifecycle.
//!
//! MBR-201: build a per-user Membrane supervisor.

use crate::error::{Result, SupervisorError};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::path::Path;

/// Current lease schema version. Bump on incompatible shape changes; the resident refuses
/// unknown versions.
pub const SUPERVISOR_LEASE_SCHEMA_VERSION: u32 = 1;

/// Supervisor-issued lease carried by the resident child. The supervisor mints a fresh
/// lease every time it (re)spawns the resident so a restart advances the lease identity
/// without an installation rotation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SupervisorLeaseV1 {
    pub schema_version: u32,
    /// Stable supervisor instance id. Generated by the supervisor on first boot.
    pub supervisor_instance_id: String,
    /// Monotonic issuance counter; incremented on every respawn.
    pub issuance: u64,
    /// Resident PID the supervisor expects to find bound to the loopback port. The
    /// resident may compare against its own PID before serving supervisor-issued
    /// commands; the supervisor trusts this value because only it owns the lease file.
    pub resident_pid_expected: u32,
    /// Loopback port the resident must bind.
    pub loopback_port: u16,
    /// RFC 3339 instant the lease was minted. Best-effort; not used as authority.
    pub minted_at: String,
    /// `sha256:<hex>` of the canonical JSON of the lease body. Self-integrity so a
    /// partially-written file cannot be acted on.
    pub content_digest: String,
}

impl SupervisorLeaseV1 {
    /// Build a lease for the given supervisor instance. The caller fills in
    /// `resident_pid_expected` once the resident is actually running, then republishes.
    pub fn mint(
        supervisor_instance_id: impl Into<String>,
        issuance: u64,
        resident_pid_expected: u32,
        loopback_port: u16,
        minted_at: impl Into<String>,
    ) -> Self {
        let mut lease = Self {
            schema_version: SUPERVISOR_LEASE_SCHEMA_VERSION,
            supervisor_instance_id: supervisor_instance_id.into(),
            issuance,
            resident_pid_expected,
            loopback_port,
            minted_at: minted_at.into(),
            content_digest: String::new(),
        };
        lease.content_digest = lease.compute_digest();
        lease
    }

    /// Recompute the canonical digest. Exposed so tests can verify the published lease is
    /// internally consistent.
    pub fn compute_digest(&self) -> String {
        let mut clone = self.clone();
        clone.content_digest = String::new();
        let canonical = membrane_protocol::canonical_json_of(&clone);
        format!("sha256:{}", hex_lower(&canonical))
    }

    /// Validate the lease's self-integrity. Returns `Err` if the recorded digest does not
    /// match the recomputed one.
    pub fn verify_self_integrity(&self) -> Result<()> {
        let expected = self.compute_digest();
        if expected != self.content_digest {
            return Err(SupervisorError::InvalidConfig {
                reason: format!(
                    "supervisor lease digest mismatch: recorded={} computed={}",
                    self.content_digest, expected
                ),
            });
        }
        if self.schema_version != SUPERVISOR_LEASE_SCHEMA_VERSION {
            return Err(SupervisorError::InvalidConfig {
                reason: format!(
                    "unsupported supervisor lease schema_version {} (expected {})",
                    self.schema_version, SUPERVISOR_LEASE_SCHEMA_VERSION
                ),
            });
        }
        if self.loopback_port < 1024 {
            return Err(SupervisorError::InvalidConfig {
                reason: format!(
                    "supervisor lease loopback_port {} is privileged",
                    self.loopback_port
                ),
            });
        }
        Ok(())
    }
}

/// Discovery record the supervisor publishes alongside the lease. Client adapters read
/// this to learn the loopback port, the supervisor's instance id, and the lease path
/// (which they can validate before submitting work). The file is JSON, ordered
/// alphabetically, no whitespace.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SupervisorEndpointV1 {
    pub schema_version: u32,
    pub supervisor_instance_id: String,
    pub lease_issuance: u64,
    pub loopback_port: u16,
    pub lease_path: String,
    pub minted_at: String,
}

pub const SUPERVISOR_ENDPOINT_SCHEMA_VERSION: u32 = 1;

impl SupervisorEndpointV1 {
    pub fn from_lease(lease: &SupervisorLeaseV1, lease_path: &Path) -> Self {
        Self {
            schema_version: SUPERVISOR_ENDPOINT_SCHEMA_VERSION,
            supervisor_instance_id: lease.supervisor_instance_id.clone(),
            lease_issuance: lease.issuance,
            loopback_port: lease.loopback_port,
            lease_path: lease_path.display().to_string(),
            minted_at: lease.minted_at.clone(),
        }
    }

    pub fn verify_self_integrity(&self) -> Result<()> {
        if self.schema_version != SUPERVISOR_ENDPOINT_SCHEMA_VERSION {
            return Err(SupervisorError::InvalidConfig {
                reason: format!(
                    "unsupported supervisor endpoint schema_version {} (expected {})",
                    self.schema_version, SUPERVISOR_ENDPOINT_SCHEMA_VERSION
                ),
            });
        }
        if self.loopback_port < 1024 {
            return Err(SupervisorError::InvalidConfig {
                reason: format!(
                    "supervisor endpoint loopback_port {} is privileged",
                    self.loopback_port
                ),
            });
        }
        Ok(())
    }
}

/// Atomic write helper. Writes to `path.tmp` then renames so a half-written lease cannot
/// be parsed. If the parent directory is missing, creates it.
pub fn atomic_write(path: &Path, body: &[u8]) -> Result<()> {
    let parent = path.parent().ok_or_else(|| SupervisorError::Io {
        path: path.to_path_buf(),
        reason: "lease path has no parent directory".to_string(),
    })?;
    std::fs::create_dir_all(parent).map_err(|error| SupervisorError::Io {
        path: parent.to_path_buf(),
        reason: format!("create lease parent directory: {error}"),
    })?;
    let tmp_name = format!(
        ".{}.tmp",
        path.file_name()
            .and_then(|name| name.to_str())
            .unwrap_or("lease")
    );
    let tmp = parent.join(tmp_name);
    std::fs::write(&tmp, body).map_err(|error| SupervisorError::PublishFailed {
        artifact: "lease/tmp",
        path: tmp.clone(),
        reason: format!("write tmp lease: {error}"),
    })?;
    std::fs::rename(&tmp, path).map_err(|error| SupervisorError::PublishFailed {
        artifact: "lease",
        path: path.to_path_buf(),
        reason: format!("rename tmp lease: {error}"),
    })?;
    Ok(())
}

/// Publish a fresh lease + sibling endpoint file. Returns the freshly-built lease so the
/// caller can hand it to the resident.
pub fn publish_lease(
    lease_path: &Path,
    endpoint_path: &Path,
    supervisor_instance_id: &str,
    issuance: u64,
    resident_pid_expected: u32,
    loopback_port: u16,
    minted_at: &str,
) -> Result<SupervisorLeaseV1> {
    let lease = SupervisorLeaseV1::mint(
        supervisor_instance_id,
        issuance,
        resident_pid_expected,
        loopback_port,
        minted_at,
    );
    let body = serde_json::to_vec(&lease).map_err(|error| SupervisorError::PublishFailed {
        artifact: "lease",
        path: lease_path.to_path_buf(),
        reason: format!("serialize lease: {error}"),
    })?;
    atomic_write(lease_path, &body)?;

    let endpoint = SupervisorEndpointV1::from_lease(&lease, lease_path);
    let endpoint_body =
        serde_json::to_vec(&endpoint).map_err(|error| SupervisorError::PublishFailed {
            artifact: "endpoint",
            path: endpoint_path.to_path_buf(),
            reason: format!("serialize endpoint: {error}"),
        })?;
    atomic_write(endpoint_path, &endpoint_body)?;
    Ok(lease)
}

fn hex_lower(input: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(input.as_bytes());
    let digest = hasher.finalize();
    let mut hex = String::with_capacity(digest.len() * 2);
    for byte in digest.iter() {
        hex.push_str(&format!("{:02x}", byte));
    }
    hex
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lease_minting_is_deterministic_for_equal_inputs() {
        let a = SupervisorLeaseV1::mint("sup-1", 1, 4242, 47851, "2026-08-07T12:00:00Z");
        let b = SupervisorLeaseV1::mint("sup-1", 1, 4242, 47851, "2026-08-07T12:00:00Z");
        assert_eq!(a, b);
        assert!(a.content_digest.starts_with("sha256:"));
    }

    #[test]
    fn different_issuance_yields_different_digest() {
        let a = SupervisorLeaseV1::mint("sup-1", 1, 4242, 47851, "2026-08-07T12:00:00Z");
        let b = SupervisorLeaseV1::mint("sup-1", 2, 4242, 47851, "2026-08-07T12:00:00Z");
        assert_ne!(a.content_digest, b.content_digest);
        assert_ne!(a, b);
    }

    #[test]
    fn lease_self_verifies() {
        let lease = SupervisorLeaseV1::mint("sup-1", 1, 4242, 47851, "2026-08-07T12:00:00Z");
        assert!(lease.verify_self_integrity().is_ok());
    }

    #[test]
    fn tampered_lease_fails_self_verification() {
        let mut lease = SupervisorLeaseV1::mint("sup-1", 1, 4242, 47851, "2026-08-07T12:00:00Z");
        lease.loopback_port = 47852;
        let err = lease.verify_self_integrity().unwrap_err();
        assert_eq!(err.label(), "invalid-config");
    }

    #[test]
    fn unknown_schema_version_rejected() {
        let mut lease = SupervisorLeaseV1::mint("sup-1", 1, 4242, 47851, "2026-08-07T12:00:00Z");
        lease.schema_version = 99;
        lease.content_digest = lease.compute_digest();
        let err = lease.verify_self_integrity().unwrap_err();
        assert!(format!("{err}").contains("schema_version 99"));
    }

    #[test]
    fn endpoint_inherits_lease_fields_and_path() {
        let lease = SupervisorLeaseV1::mint("sup-7", 11, 999, 47851, "2026-08-07T12:00:00Z");
        let endpoint =
            SupervisorEndpointV1::from_lease(&lease, Path::new("/var/lib/membrane/lease.json"));
        assert_eq!(
            endpoint.supervisor_instance_id,
            lease.supervisor_instance_id
        );
        assert_eq!(endpoint.lease_issuance, lease.issuance);
        assert_eq!(endpoint.loopback_port, lease.loopback_port);
        assert_eq!(endpoint.lease_path, "/var/lib/membrane/lease.json");
        assert!(endpoint.verify_self_integrity().is_ok());
    }

    #[test]
    fn publish_writes_both_files_atomically() {
        let temp = tempfile::tempdir().unwrap();
        let lease_path = temp.path().join("lease.json");
        let endpoint_path = temp.path().join("endpoint.json");
        let lease = publish_lease(
            &lease_path,
            &endpoint_path,
            "sup-1",
            1,
            4242,
            47851,
            "2026-08-07T12:00:00Z",
        )
        .unwrap();

        // Lease round-trips and verifies.
        let raw = std::fs::read(&lease_path).unwrap();
        let parsed: SupervisorLeaseV1 = serde_json::from_slice(&raw).unwrap();
        assert_eq!(parsed, lease);
        parsed.verify_self_integrity().unwrap();

        let raw_endpoint = std::fs::read(&endpoint_path).unwrap();
        let parsed_endpoint: SupervisorEndpointV1 = serde_json::from_slice(&raw_endpoint).unwrap();
        assert_eq!(parsed_endpoint.loopback_port, 47851);
        parsed_endpoint.verify_self_integrity().unwrap();

        // tmp file is gone (atomic rename succeeded).
        assert!(!temp.path().join(".lease.json.tmp").exists());
    }

    #[test]
    fn publish_creates_missing_parent() {
        let temp = tempfile::tempdir().unwrap();
        let deep = temp.path().join("a/b/c/lease.json");
        let endpoint = temp.path().join("a/b/c/endpoint.json");
        publish_lease(
            &deep,
            &endpoint,
            "sup-1",
            1,
            4242,
            47851,
            "2026-08-07T12:00:00Z",
        )
        .unwrap();
        assert!(deep.is_file());
        assert!(endpoint.is_file());
    }
}
